### ISSUE TITLE
New contracts for Jakarta EE 9

### ISSUE THREAD

**Issue by bjhargrave** [osgi/osgi#124]
Jakarta EE 9 is renaming packages from `javax.` to `jakarta.`.

We need to define new `Jakarta*` contracts for Jakarta EE 9.

**Comment by maho7791** [comment]
This would also lead to coresponding changes in specifications like HttpService, HttpWhiteboard, JaxRsWhiteboard, CDI.

Do we have plans for this? Especially , how to deal with the former 'javax' namespace support.

**Comment by maho7791** [comment]
I think this belongs to #54

**Comment by bjhargrave** [comment]
> This would also lead to coresponding changes in specifications like HttpService, HttpWhiteboard, JaxRsWhiteboard, CDI.

Those are separate items than this one. You will see this mentioned in the "Future Work" section of <https://projects.eclipse.org/proposals/osgi-specification-project>.

> I think this belongs to #54

The contracts are independent of updating OSGi specifications to use jakarta API.
