### ISSUE TITLE
DS: Support Optional for field and constructor injection

### ISSUE THREAD

**Issue by bjhargrave** [osgi/osgi#143]
I kind of like the idea of `Optional<T>` for field injection. It is short hand for `cardinality=ReferenceCardinality.OPTIONAL`.

Since R8 supports, Java 8 as the base language level, we can now add support for `Optional` as a field (and constructor) injection type. Bnd can infer the actual service type from the generic T.

So

```java
@Reference
Optional<Foo> foo;
```

would be a static optional reference to a `Foo` service, The `foo` field would be injected with either an empty `Optional` if there is no target `Foo` service, or a non-empty `Optional` with the bound `Foo` service. Like all static references, the `foo` field would not be changed by SCR during the life cycle of the component instance. This can also be used in constructor injection with a `Optional<Foo>` constructor parameter.

```java
@Reference
volatile Optional<Foo> foo;
```

would be a dynamic optional reference to a `Foo` service. The foo field would be injected with either an empty `Optional` if there is no target `Foo` service, or a non-empty `Optional` with the bound `Foo` service. Like all dynamic references, the value of the `foo` field can be changed by SCR at any time during the life cycle of the component instance. So when the component wishes to use the field, it should copy the field's value into a local variable before inspection and use.

```java
Optional<Foo> localFoo = foo;
if (localFoo.isPresent()) { do something with localFoo; }
```

**Comment by tjwatson** [comment]
I started to look at implementing this in Felix SCR and have some questions

1. Is `Optional` support is only valid for field and constructor injection and  should not be valid for bind/unbind method arguments?  It makes no sense for bind/unbind methods.
2. The `Optional` type field/constructorArg is valid for `OPTIONAL("0..1)`.  It will be invalid for `MULTIPLE("0..n")` and `AT_LEAST_ONE("1..n")`.  What about `MANDATORY("1..1")`?
3. Albeit this is a degenerate usecase - but with R7 it is possible for a service to be registered under the `objectClass` of `java.lang.Optional` and it is possible for a DS component to use field/constructorArg types of `Optional` to get injected with the `Optional` object registered as a service.  I assume if the reference `interface` attribute is `java.lang.Optional` then things will continue to behave this way and SCR must not wrap the `Optional` service object in another `Optional<Optional<?>>` object to inject into the component.

**Comment by bjhargrave** [comment]
> * Is `Optional` support is only valid for field and constructor injection and  should not be valid for bind/unbind method arguments?  It makes no sense for bind/unbind methods.
> 

Only for field and constructor injection.

> * The `Optional` type field/constructorArg is valid for `OPTIONAL("0..1)`.  It will be invalid for `MULTIPLE("0..n")` and `AT_LEAST_ONE("1..n")`.  What about `MANDATORY("1..1")`?
> 

It is supported for unary references which include 1..1. I did not see any reason to exclude 1..1, But the Reference annotation will default to 0..1 cardinality for annotated fields and constructor parameters of type Optional.

> * Albeit this is a degenerate usecase - but with R7 it is possible for a service to be registered under the `objectClass` of `java.lang.Optional` and it is possible for a DS component to use field/constructorArg types of `Optional` to get injected with the `Optional` object registered as a service.  I assume if the reference `interface` attribute is `java.lang.Optional` then things will continue to behave this way and SCR must not wrap the `Optional` service object in another `Optional<Optional<?>>` object to inject into the component.

Like for ServiceReference, etc., if the actual service type of the referenced service is `Optional` then the actual service object is injected rather than an Optional holding the service object.
