### ISSUE TITLE
[Rest Management] defines what appears to be an illegal JSON Object structure for `application/org.osgi.bundles+json`

### ISSUE THREAD

**Issue by rotty3000** [osgi/osgi#152]
The Rest Management Specification defines what appears to be an illegal JSON Object structure for the `application/org.osgi.bundles+json` content type:
```
{
   [bundleURI, bundleURI, ..., bundleURI]
}
```
an object whose only member is an array!?!

Isn't this illegal since JSON Objects require members to have keys. Is this known, maybe we have errata for this?

> https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.rest.html#d0e116483

**Comment by rotty3000** [comment]
for that matter `application/org.osgi.bundles.representations+json` is also illegal:
```
{
    [BUNDLE REPRESENTATION, BUNDLE REPRESENTATION, ..., BUNDLE REPRESENTATION]
}
```

> https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.rest.html#service.rest-bundle.representations.list.representation

**Comment by juergen-albert** [comment]
I don't like constructs like this, but I'm not sure if this is really illegal. We stumbled upon such things quite often in the wild.
According to [json.org] it would be invalid, but all the RFCs I've seen so far don't show such a construct as illegal. I'd love to see any hard evidence to declarer this the cancer it is. So if somebody knows more, please share the source.

We could at least declare it as bad form and avoid such a construct. I would strongly support such a change.

**Comment by bjhargrave** [comment]
Interesting, the REST RI and CT seems to be fine with this...

**Comment by rotty3000** [comment]
I have not found a JSON serializer that will create this construct. Not sure how the RI accomplishes that. I need to investigate.

**Comment by rotty3000** [comment]
I cannot find a way to describe the model in terms of Open API schema. 

For this reason I'd like to propose that the model be changed to one where the root is an object with one property whose name suites the representation type:
e.g.
For Content-Type: application/org.osgi.bundles+json
```
{
   'bundles': [bundleURI, bundleURI, ..., bundleURI]
}
```
For Content-Type: application/org.osgi.bundles.representations+json
```
{
    'bundles': [BUNDLE REPRESENTATION, BUNDLE REPRESENTATION, ..., BUNDLE REPRESENTATION]
}
```
For Content-Type: application/org.osgi.services+json
```
{
   'services': [serviceURI, serviceURI, ..., serviceURI]
}
```
For Content-Type: org.osgi.services.representations+json
```
{
   'services': [SERVICE REPRESENTATION, SERVICE REPRESENTATION, ..., SERVICE REPRESENTATION]
}
```

The side benefit of this is that if an implementation chooses to add supporting properties to the result there is no collision (no need to change the spec really, which is already possible with all the other representations due to their simple definition):

e.g. adding pagination:
```
{
    'services': [
        ... limit to 20 ...
    ],
    "page": {
        // defaults with no paging
        "size": 1756,
        "totalElements": 1756,
        "totalPages": 1,
        "number": 1
    },
    "_links": {
        "first": {
            "href": "http://localhost:8080/rms/framework/services/representations?page=0&size=20"
        },
        "prev": {
            "href": "http://localhost:8080/rms/framework/services/representations?page=0&size=20"
        },
        "self": {
            "href": "http://localhost:8080/rms/framework/services/representations?page=1&size=20"
        },
        "next": {
            "href": "http://localhost:8080/rms/framework/services/representations?page=2&size=20"
        },
        "last": {
            "href": "http://localhost:8080/rms/framework/services/representations?page=88&size=20"
        }
    }
}
```

**Comment by bjhargrave** [comment]
> I'd like to propose that the model be changed

How would this be backwards compatible to clients receiving the payload?

Wouldn't we need new content types to request this new format?

`Content-Type: application/org.osgi.bundles.representations.v2+json`

**Comment by rotty3000** [comment]
I'm suggesting that we consider the current state as broken!

**Comment by bjhargrave** [comment]
> I'm suggesting that we consider the current state as broken!

That may be true, but we still have a published spec and an RI and TCK which use the current state. 

https://github.com/eclipse/concierge/tree/master/bundles/org.eclipse.concierge.service.rest is an implementation of the REST spec. What does it do for these JSON objects?

**Comment by rotty3000** [comment]
You'll notice that the CT doesn't even follow the representation specified 

https://github.com/osgi/osgi/blob/063c29cb12eadaab59df75dfa967978c8052c4da/org.osgi.test.cases.rest/src/org/osgi/test/cases/rest/junit/RestServiceJSONTestCase.java#L816

You can see it actually uses a JSONArray which means that the implementation actually returns:
```
[bundleURI, bundleURI, ..., bundleURI]
```
and not
```
{
   [bundleURI, bundleURI, ..., bundleURI]
}
```

**Comment by bjhargrave** [comment]
I guess someone will need to dig into this to under stand what the RI does, what the TCK does and what Concierge's impl does to see if anyone follows the spec.

**Comment by rotty3000** [comment]
it sends a JSON array 

https://github.com/eclipse/concierge/blob/0378bf822791ce971c428c8fd9ee6d1139eb7135/bundles/org.eclipse.concierge.service.rest/src/org/osgi/impl/service/rest/resources/AbstractOSGiResource.java#L247-L256

**Comment by rotty3000** [comment]
I'd be ok with changing the content type to being just an array. At least that's usable if not ideal.

On the other hand, if it's broken as defined, I suggest fixing it in the best possible way, and using an array as the representation has severe limitations. Its rather hard (if not impossible) to optimize for very large result set.

**Comment by bjhargrave** [comment]
> I'd be ok with changing the content type to being just an array. 

Agree. I think the fix is to remove the surrounding `{` `}` from the arrays.

> At least that's usable if not ideal.

An array is a legal JSON document, no?

**Comment by bjhargrave** [comment]
> On the other hand, if it's broken as defined, I suggest fixing it in the best possible way, and using an array as the representation has severe limitations. Its rather hard (if not impossible) to optimize for very large result set.

This sounds more like a new representation form and is a spec change not an errata.

**Comment by rotty3000** [comment]
Aright' let's just go with array.

**Comment by bjhargrave** [comment]
Project call: Agreed to return simple array.

Need errata for R7.
