### ISSUE TITLE
[Rest Management] 137.3.2.2 POST with Location String ambiguous description of the response body

### ISSUE THREAD

**Issue by rotty3000** [osgi/osgi#153]
Section `137.3.2.2 POST with Location String` describes the following response body:

> The body of the response is Bundle Representation of the newly installed bundle. The following status codes can be returned:
>
>    200 (OK): the bundle has been successfully installed and the body of the response contains the URI.

In one line it says `The body of the response is Bundle Representation of the newly installed bundle`, and in the next it says `the body of the response contains the URI`.

See https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.rest.html#service.rest-bundles.post.location

**Comment by bjhargrave** [comment]
Project call: Also in 137.3.2.3. 

Recommended fix is to remove reference to body containing URI. The response contains the representation.

**Comment by bjhargrave** [comment]
Also need an errata for https://docs.osgi.org/specification/errata.html#release-7
