### ISSUE TITLE
OSGi Features (was RFC 241)

### ISSUE THREAD

**Issue by bosschaert** [osgi/osgi#162]
OSGi Features Specifiaction

Requirements: https://github.com/osgi/design/blob/main/rfps/rfp-0188-Features.pdf
Design: https://github.com/osgi/design/blob/main/rfcs/rfc0241/rfc-0241-Features.pdf

Initial spec text can already be found at https://github.com/osgi/osgi/blob/fm-spec/osgi.specs/docbook/708/
Initial API can be found here: TBD
Initial Compliance tests are found here: TBD

**Comment by bjhargrave** [comment]
Features design work is already complete prior to the new process. So we now open tracking issues for the specification, implementation, and tck work.
