### ISSUE TITLE
OSGi Messaging (was RFC 246)

### ISSUE THREAD

**Issue by maho7791** [osgi/osgi#173]
OSGi Messaging Specifiaction

Requirements: https://github.com/osgi/design/blob/main/rfps/rfp-0192-Messaging.pdf
Design: https://github.com/osgi/design/blob/main/rfcs/rfc0246/rfc-0246-Messaging.pdf

Initial spec text can already be found: TBD 
Initial API can be found here: TBD
Initial Compliance tests are found here: TBD

**Comment by bjhargrave** [comment]
Dup of #172
