### ISSUE TITLE
Type Safe Eventing specification writing

### ISSUE THREAD

**Issue by bjhargrave** [osgi/osgi#183]
Type Safe Eventing design work is already complete prior to the new process. So we now open tracking issues for the specification, implementation, and tck work.

_Originally posted by @bjhargrave in https://github.com/osgi/osgi/issues/171#issuecomment-823599432_

**Comment by timothyjward** [comment]
Work is mostly complete, ready for @juergen-albert to turn into a TCK

**Comment by bjhargrave** [comment]
The specification still has an unresolved `remark`:

> 157.3.1 ### This grammar is more lenient than it might be to allow full compatiblity with Event Admin. Just using "topic ::= identifier ( '/' identifier ) *" would be simpler but disallow "-" in tokens

**Comment by bjhargrave** [comment]
Spec project call: Remove remark. Remove `| '_'` from production since jletterordigit already include it.
