### ISSUE TITLE
Type Safe Eventing implementation development

### ISSUE THREAD

**Issue by bjhargrave** [osgi/osgi#184]
Type Safe Eventing design work is already complete prior to the new process. So we now open tracking issues for the specification, implementation, and tck work.

_Originally posted by @bjhargrave in https://github.com/osgi/osgi/issues/171#issuecomment-823599432_

**Comment by timothyjward** [comment]
A prototype implementation is available in Apache Aries. Any fixes identified by the TCK can be applied there.

**Comment by bjhargrave** [comment]
Now that we have an RC1 build of org.osgi.service.typedevent in Maven Central, when do we expect an RC/Milestone build of the compatible implementation in Maven Central?
