### ISSUE TITLE
Type Safe Eventing tck development

### ISSUE THREAD

**Issue by bjhargrave** [osgi/osgi#185]
Type Safe Eventing design work is already complete prior to the new process. So we now open tracking issues for the specification, implementation, and tck work.

_Originally posted by @bjhargrave in https://github.com/osgi/osgi/issues/171#issuecomment-823599432_

**Comment by stbischof** [comment]
While development the tck lives here 
https://github.com/geckoprojects-org/osgi
Branche: typedevent_tck
