### ISSUE TITLE
DS 1.5 implementation development

### ISSUE THREAD

**Issue by bjhargrave** [osgi/osgi#189]
Track development of an implementation of the DS 1.5 spec.

- [x] AnyService
- [x] Optional
- [x] Satisfying conditions
- [x] Component properties from property and properties elements take precedence over the target property from the target attribute of reference elements.

**Comment by tjwatson** [comment]
Implementation is being done in felix in a branch

https://github.com/apache/felix-dev/tree/scrR8

**Comment by bjhargrave** [comment]
See also the following Bnd issues for supporting new DS 1.5 features:

* https://github.com/bndtools/bnd/issues/4657
* https://github.com/bndtools/bnd/issues/4658

**Comment by bjhargrave** [comment]
> See also the following Bnd issues for supporting new DS 1.5 features:

These Bnd issues are now fixed by https://github.com/bndtools/bnd/pull/4691

**Comment by bjhargrave** [comment]
DS 1.5 TCK updates for Optional support found bugs in the current DS 1.5 impl. 2 new tests are now failing.

**Comment by bjhargrave** [comment]
DS 1.5 TCK updates for component property precedence found a bug in the current DS 1.5 impl. 1 new test is now failing.

**Comment by bjhargrave** [comment]
Felix SCR R8 passes TCK

**Comment by bjhargrave** [comment]
Now that we have an RC1 build of org.osgi.service.component in Maven Central, when do we expect an RC/Milestone build of the compatible implementation in Maven Central?

**Comment by tjwatson** [comment]
I just published the RC1 release of SCR: https://repo1.maven.org/maven2/org/apache/felix/org.apache.felix.scr/2.2.0-RC1/

I'll get a PR going to use it instead of the snapshot.

**Comment by tjwatson** [comment]
PR #325 updated to use Felix SCR 2.2.0-RC1 release.  This can be considered the compatible implementation for the final OSGi R8 Declarative Services implementation.

**Comment by bjhargrave** [comment]
Closing as we use RC1.
