### ISSUE TITLE
Resource Enforcement

### ISSUE THREAD

**Issue by jjh-aicas** [osgi/osgi#194]
This was [rfp-0189-Resource-Enforcement](https://github.com/osgi/design/blob/main/rfps/rfp-0189-Resource-Enforcement.pdf)

The purpose of this RFP is to enable the enforcement of resource restriction on bundles to ensure the robustness of the framework.  The resources of a bundle may include CPU use, memory consumption, number of threads, network connections, and other limited resources.  These are not just limited to the runtime environment (Java VM, OSGi Framework, etc), but can also include any resource required by a service. 

RTSJ 2.0 and the Java security manager already provide mechanisms for such resource enforcement at a granular level, e.g., threads.  Industrial solutions also make them available at the bundle level.  This RFP advocates standardizing the set of features and their API in OSGi specifications.

This API should complement the existing resource monitoring API.

**Comment by bjhargrave** [comment]
@kaihackbarth Can you confirm if this RFP was approved? We think it was final and may have been voted on. You sent an email Jul 18, 2018 about voting.

**Comment by bjhargrave** [comment]
@kaihackbarth ??

**Comment by kaihackbarth** [comment]
@bjhargrave I can confirm it has been approved as I did send an E-Mail about the approved RFP to Azul. However I don't seem to have access to the email with the voting results. Unfortunately our mailboxes at Bosch were limited to 3GB. Now with Office365 we don't have this problem anymore...

**Comment by bjhargrave** [comment]
@jjh-aicas Does aicas plan to work on this at some point? Not sure how this will fit in with the planned deprecation and removal of SecurityManager in a future Java release.

**Comment by jjh-aicas** [comment]
This issue is still in the works.

**Comment by jjh-aicas** [comment]
> @jjh-aicas Does aicas plan to work on this at some point? Not sure how this will fit in with the planned deprecation and removal of SecurityManager in a future Java release.

The new module system provides new means of protecting APIs via module shadowing.
