### ISSUE TITLE
Provide snapshot-builds

### ISSUE THREAD

**Issue by stbischof** [osgi/osgi#199]
I am trying to develop some external tooling on top of the osgi-feature spec. It would help me, if there would be a snapshot build in any repo. 

Is there anywhere a Repo with the snapshot build, or could you please add one?

**Comment by bjhargrave** [comment]
The snapshot API artifacts are published at https://oss.sonatype.org/content/repositories/snapshots/. See the listing for org.osgi groupId at https://oss.sonatype.org/content/repositories/snapshots/org/osgi/.

The complete artifact set for each build is an artifact attached to the GitHub Action build. See https://github.com/osgi/osgi/actions/runs/809269970#artifacts for example. You want the "OSGi-Generated-Repo" artifact.

**Comment by bjhargrave** [comment]
In the future, these sorts of questions should be asked in the osgi-dev@eclipse.org mail list. Not as an issue here. Thanks.
