### ISSUE TITLE
[Features] Use Optional-API in Features

### ISSUE THREAD

**Issue by stbischof** [osgi/osgi#207]
There are several optional fields in Features.
This are the methods where an `Optional<String>` as return value could be a good way to go.

```
Features::getName
Features::getDescription
Features::getVendor
Features::getLicense
Features::getName
Features::getDocURL
Features::getCopyright
Features::getCategories
Features::getSCM
ID::getType
ID::getClassifier
FeatureConfiguration::getFactoryPid
```

Extensions: https://osgi.github.io/osgi/cmpn/util.features.html#d0e167706
At the moment this methods also would return null when used in combination with the wrong `type - getType`

This could also handled by an Optional. An other way for this would be to throw a `UnsupportedOperationException`
``` 
FeatureExtension::getJSON	(Optional<Stirng>)
FeatureExtension::getText	(Optional<List<Stirng>>)
FeatureExtension::getArtifacts	(Optional<List<ID>>)
```

**Comment by bosschaert** [comment]
I played a bit with this and I think it can work. I don't think `Optional<>` would make the API awkward to use, as long as you properly follow the Optional-provided APIs. You can see what the changes would look like here: https://github.com/osgi/osgi/commit/2a0e833ffece1ba6f194d1b6c767fecfc2b36ec6
