### ISSUE TITLE
[Features] extract Metadata fields from Feature.class into a new FeatureMetadata.class

### ISSUE THREAD

**Issue by stbischof** [osgi/osgi#208]
At the moment there are this Header/Metadata fields in `Feature.class`
Features::getName
Features::getDescription
Features::getVendor
Features::getLicense
Features::getName
Features::getDocURL
Features::getCopyright
Features::getCategories
Features::getSCM

They could be extracted in a `FeatureMetadata.class`.that also provides an additional `Map<String,String>` for additional custom Metadatas

**Comment by bosschaert** [comment]
Spec call: decision to leave these directly in the feature rather than putting them in a sub-object. 
Custom metadata can already be provided using feature extensions.
