### ISSUE TITLE
[Feature] Feature-Json should provide resource-version and JSON Schema 

### ISSUE THREAD

**Issue by stbischof** [osgi/osgi#209]
A Global property in the Feature-Json specifying the version of the resource format might also be usefull. We have this in
- Configurator: `":configurator:resource-version" : 1,`
- Manifest: `Manifest-Version: 1.0`

From @bosschaert: 
> We could also use a JSON Schema and encode the version in the schema URL, similar to how this is 
> done for XML Schemas in the Remote Service Admin spec https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.remoteserviceadmin.html#d0e92612

extracted from #179

**Comment by bjhargrave** [comment]
We should just add a version entry like configurator for now.
