### ISSUE TITLE
[Features] Features - Define `bundles` more general with uris

### ISSUE THREAD

**Issue by stbischof** [osgi/osgi#210]
Maybe this had been discussed before, so sorry if this is in any kind a duplicate.

At the Moment a Feature holds bundles and the bundles are definded by G:A:V coordinates.
An other approach would be to hold `artifacts` that are defined using an URI. These artifacts must have a type that is by default `bundle`.

This would allow to have not just bundles. A feature could also reference a oci-container as an artifact.
It would allow to add requirements/capabilities do every type of artifacts and make them resolveable agains eachother.
`A Feature with the Runtime-Bundles that needs an Mongo-DB resolved agains an other Feature with the oci-container of an MongoDB in the right version`

**Comment by bosschaert** [comment]
Spec call: having a pluggable URI makes it harder to unambiguously define what the ID means. And to make features with these usable by users at large it would need some plugin mechanism to register custom handlers. This would be a lot to add to the features spec right now, and probably deserves a proper requirements discussion to better understand the use-cases. So if this is something to pursue, the best path forward would be to a https://github.com/osgi/osgi/blob/main/CONTRIBUTING.md#requirements-discussion as per the spec process and discuss further there.

Note that wrt to non-bundle artifacts, special URI schemes could already be used in JSON and Text extensions.
