### ISSUE TITLE
[Features Impl] Handle external dependencies while being usable in both an OSGi and non-OSGi runtime

### ISSUE THREAD

**Issue by bosschaert** [osgi/osgi#216]
For the Features spec implementation we have the following constraints.

1. The implementation must be able to do the following

* Parse JSON
* Parse Configurator JSON (which is a specialized JSON format)

The best way to handle these points above is to be able to use existing implementations of these.

2. Furthermore, the Features spec implementation needs to be usable from both inside OSGi as well as in a plain Java environment. This is because commandline tools, or build/developer tooling plugins must be able to work with features, in addition to OSGi runtime based environments.

**Comment by bosschaert** [comment]
I think there are 2 possible ways to address the constraints

1. Via a Util Spec. A util spec in OSGi normally provides an implementation alongside the spec so it can be used in either environment. In this case the Util Spec would have a dependency on a separate JSON parser and a separate Configurator parser.

or

2. Alternatively via a 'regular' OSGi spec. In that case OSGi only provides only the API. To make this usable in a POJO environment the spec can mandate that implementation classes are registered via /META-INF/services as well as via the service registry to make them usable in both contexts.

**Comment by stbischof** [comment]
We have the same on the Writer site, where we serialize the Java Feature model into a JSON..

**Comment by bjhargrave** [comment]
A util package should not have dependencies on 3rd party jars. All of the other util packages depend only on the JRE, the core packages, or other util packages. For example, util.pushstream depends on util.promise which depends on util.function. util.tracker depends on core. But none of them depends upon a 3rd party jar like a JSON parser/serializer. 

If features needs such a capability, it would either needs its own private, minimal implementation, or the spec should be service.feature having interfaces which are implemented by implementations.

**Comment by bjhargrave** [comment]
Spec project call: Agreed to change to a service spec and allow bundle impls registering services and classpath/module impls using ServiceLoader to provide impls.
