### ISSUE TITLE
[TypedEvent] Clarify definition of a DTO

### ISSUE THREAD

**Issue by stbischof** [osgi/osgi#219]
The TypedEvent Spec defines:
- `DTO - A Data Transfer Object as per the OSGi DTO Specification.`  [157.1.1](https://osgi.github.io/osgi/cmpn/service.typedevent.html#d0e154027)

The Core DTO Spec:
- `The org.osgi.dto package defines the basic rules and the abstract base DTO class which Data Transfer Objects must extend. `  [57.2](https://osgi.github.io/osgi/core/framework.dto.html#d0e48305)

----
The TypedEvent Spec named the criteria of an DTO again in the section about `Type Safe Events` 

- `Type Safe Event classes are expected to conform to OSGi DTO rules. The architecture of OSGi DTOs is described in OSGi Core Release 8. All methods, all static fields, and any non public instance fields of an event object must be ignored by the Typed Event Service when processing the Event data.` [157.2.1](https://osgi.github.io/osgi/cmpn/service.typedevent.html#d0e154094)

This names all criteria, but not the `must extends org.osgi.dto.DTO`.

In all examples the TypedEvents also does not extend DTO 
```
public class ExampleEvent {
    public String message;
}
```
The Type of the Event <T> in the TypedEventHandler does also not extend DTO
https://github.com/osgi/osgi/blob/da5c76b9dea1e170b80e41f8ec1f8429762d784e/org.osgi.service.typedevent/src/org/osgi/service/typedevent/TypedEventHandler.java#L51-L63

How strict is the word DTO used? 
Maybe some sentence would help, that explicit allows to not extend DTO.

**Comment by bjhargrave** [comment]
@stbischof See https://osgi.github.io/osgi/cmpn/ for the most up to date draft Compendium R8 specification

**Comment by bjhargrave** [comment]
@stbischof I have removed the old Compendium R8 drafts on docs.osgi.org and updated the site to link to the latest drafts built by github actions: https://osgi.github.io/osgi/cmpn/

Make sure to use this URL in the future for the draft Cmpn R8 spec.

**Comment by stbischof** [comment]
I just followed the [docs.osgi.org/](docs.osgi.org/)  on the main [osgi-github](https://github.com/osgi/osgi) site. So thank you for updating the link! 

I updated the links in this issue.

**Comment by bjhargrave** [comment]
Fixed by #242
