### ISSUE TITLE
[TypedEvent] Topic-grammar vs automatically generated Topics 

### ISSUE THREAD

**Issue by stbischof** [osgi/osgi#225]
If I am reading the grammar the right way, no special character like `$` is allowed.

Grammar:
```
      topictoken  :: ( jletterordigit | '_' | '-' ) +
      
      topic       ::= topictoken ( '/' topictoken ) *
```

Automatically generated Topics are generated from the className of the Event in this way:
```
String topicName = event.getClass().getName().replace('.', '/');
```

If the event is a nested or inner class it will generate a topic that is not valid because of the `$`.

**Comment by bjhargrave** [comment]
> jletterordigit

From https://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-3.8:

> The "Java letters" include uppercase and lowercase ASCII Latin letters A-Z (\u0041-\u005a), and a-z (\u0061-\u007a), and, for historical reasons, the ASCII underscore (_, or \u005f) and dollar sign ($, or \u0024). The $ sign should be used only in mechanically generated source code or, rarely, to access pre-existing names on legacy systems.


So the `'_'` in the topictoken production is redundant. But `$` is already included.

**Comment by stbischof** [comment]
Thank you for the fast help!

**Comment by bjhargrave** [comment]
> Would be nice to have this link in the spec

It is in the spec. That's where I got it. See [1.3.2 General Syntax Definitions](https://docs.osgi.org/specification/osgi.core/8.0.0/framework.introduction.html#framework.general.syntax). `jletterordigit` is defined and references the JLS.

**Comment by stbischof** [comment]
Sure. i meaned an direct link from cmpn to the core 
I know that there is this line 
```
  // For further information see General Syntax Definitions in Core 
```

**Comment by bjhargrave** [comment]
>  direct link from cmpn to the core

This is hard since we cannot link between specs since we make PDF and HTML versions. And we don't always know during the spec build where the URL of the HTML spec will be. There are drafts specs (built in different forks) and final specs, etc. So we rely upon humans to make the connection using words :-)

**Comment by bjhargrave** [comment]
Closing since `$` is already allowed.
