### ISSUE TITLE
[Converter] Join 2 Converter spec implementations (Felix + OSGi)

### ISSUE THREAD

**Issue by bosschaert** [osgi/osgi#227]
There are 2 implementations of the OSGi Converter Util Spec: one in Felix and one in OSGi.
They essentially originate from the same codebase so any changes and fixes have to be applied twice.

Ideally we would collapse these two implementations back into a single one.

**Comment by stbischof** [comment]
The Felix converter handles default methods of Interfaces since [PR](https://github.com/apache/felix-dev/pull/10/files)

This behavior is (afaik) not specified in the Spec (707.4.4.4.4.1 Converting to an Interface). 

We may can add some words about this topic.

**Comment by bjhargrave** [comment]
> We may can add some words about this topic.

So we may need to update the Converter spec to 1.1!

**Comment by bosschaert** [comment]
I guess the question is whether this is as small as an erratum (basically an omission in the spec) or whether it needs a proper spec revision.

**Comment by bjhargrave** [comment]
We are free to update the spec version to 1.1 to add new features. I am not sure omitting a feature is really something which can be "clarified".

**Comment by kwin** [comment]
It is already in 1.0.8! Latest is 1.0.9. Seems that 1.0.8 contains the fix from https://issues.apache.org/jira/browse/FELIX-6157 (also contained in 1.0.10 from Felix). You guys don't make it easy for consumers :-)

**Comment by kwin** [comment]
> OSGi just used its current version as the base for this release. 

Well I only see version 1.0.0 and 1.0.1 and afterwards follows 1.0.8. Obviously some versions have been skipped for no obvious reason and I assumed that is to make the version numbers between Felix and OSGi aligned (but this is obviously wrong).
