### ISSUE TITLE
org.osgi.test.cases.rest.client.js TCK fails intermittently in the CI build

### ISSUE THREAD

**Issue by bjhargrave** [osgi/osgi#250]
The org.osgi.test.cases.rest.client.js TCK fails intermittently in the CI build due to some timing error. See <https://github.com/osgi/osgi/runs/2822589008?check_suite_focus=true> for an example.

This needs to be fixed to complete the Compendium R8 release.

**Comment by bosschaert** [comment]
The problem seems to relate to some unicode mismatch:

The assertion failure is:

```
Expected
bjhargrave;email="hargrave@us.ibm.com";name="BJ Hargrave";organization=IBM;organizationUrl="https://developer.ibm.com";roles=developer;timezone="America/New_York",rotty3000;email="raymond.auge@liferay.com";name="Ray AugÃÂ©";organization="Liferay Inc.";organizationUrl="https://www.liferay.com";roles=developer;timezone="America/New_York",kriegfrj;email="fr.jkrieg@greekwelfaresa.org.au";name="Fr Jeremy Krieg";timezone="Australia/Adelaide" 

but was
bjhargrave;email="hargrave@us.ibm.com";name="BJ Hargrave";organization=IBM;organizationUrl="https://developer.ibm.com";roles=developer;timezone="America/New_York",rotty3000;email="raymond.auge@liferay.com";name="Ray AugÃ©";organization="Liferay Inc.";organizationUrl="https://www.liferay.com";roles=developer;timezone="America/New_York",kriegfrj;email="fr.jkrieg@greekwelfaresa.org.au";name="Fr Jeremy Krieg";timezone="Australia/Adelaide"
```

So the difference is in:
`name="Ray AugÃÂ©"` vs `name="Ray AugÃ©"`

One of the problems with this test is that it uses a random bundle every time, so it won't produce the same test result every run.

**Comment by bjhargrave** [comment]
> So the difference is in:
> `name="Ray AugÃ�Â©"` vs `name="Ray AugÃ©"`

Just changing the TCK to exclude this one header is just ignoring the real encoding problem. I have a PR to fix this in the test.

**Comment by bjhargrave** [comment]
And thanks to @rotty3000 for exposing this TCK bug! :-)
