### ISSUE TITLE
[pushstream] extends bound on toArray() prevents superclass arrays

### ISSUE THREAD

**Issue by kriegfrj** [osgi/osgi#262]
Executive Summary: the `extends T` on the `PushStream.toArray()` method should be removed, as it prevents you from collecting the response in an array of a superclass type.

Detail:
Forgive me if this issue has already been discussed, I've not followed the core OSGi dev closely, but I just stumbled on this in the PushStream API:

```java
<A extends T> Promise<A[]> toArray(IntFunction<A[]> generator);
```

The corresponding method in the Java streams API (which it is clearly attempting to mimic) is:

```java
<A> A[] toArray(IntFunction<A[]> generator);
```

The difference that doesn't make sense to me is why the `extends` in `A extends T` (which the Java streams API does not have)?  That makes the following code not compile:

```java
PushStream<Integer> ps = ...; 

Promise<Number[]> result = ps.toArray(Number[]::new);
```
This `toArray()` call makes perfect sense, but it will not compile because of the `extends` bound on A - only subtypes of the actual element type are allowed.

Furthermore it seems designed to allow the following code to compile:

```java
PushStream<Number> ps = ...;

Promise<Integer[]> result = ps.toArray(Integer[]::new);
```
... which seems wrong, for two reasons:

1. it will result in an `ArrayStoreExtension` if the stream has any non-integer numbers in it, and
2. due to array covariance (ie, Integer[] is a subclass of Number[]), the above code will compile anyway even if the `extends` bound were not present (a la a plain Java 8 Stream):

```java
Stream<Number> s = ...;

Integer[] result = s.toArray(Integer[]::new);
```
This compiles (even though it would be better if it didn't) because the `Stream` API doesn't have the extends bound.

So in summary, the only case that the `extends` bound seems to protect against is a case that doesn't really need protection (and in fact might be a legitimate use case in some circumstances). The case that *does* need protection (using too narrow an array and causing an `ArrayStoreException`) is not guarded against at all.

I think what this spec really wanted was this:

```java
<A super T> Promise<A[]> toArray(IntFunction<A[]> generator);
```
...however, `super` is not permitted as a bound on a type parameter in Java, and even it it were it wouldn't do what we wanted in this case because of array covariance (eg, if your return value was expecting Promise<Object[]>, the array constructor could be any subclass of Object[] and it would still compile).

If `super` were permitted, the best type-safe alternative would be this:
```java
<A super T> Promise<A[]> toArray(Class<A> elementType, IntFunction<A[]> generator);
```

But as this is not currently permitted in Java, the best fully type-safe alternative is a static wrapper method that transforms the `super` into an `extends` and makes "this" an explicit parameter:
```java
@SuppressWarnings("unchecked")
public static <A, T extends A> Promise<A[]> toArray(PushStream<T> str, Class<A> elementType) {
	return (Promise<A[]>) str.toArray(size -> (A[])Array.newInstance(elementType, size));
}
```
Unfortunately, this wrapper won't compile at the moment because of the `extends` bound.

Thoughts?

**Comment by kriegfrj** [comment]
Closed by accident...

**Comment by kriegfrj** [comment]
> If `super` were permitted, the best type-safe alternative would be this:
> 
> ```java
> <A super T> Promise<A[]> toArray(Class<A> elementType, IntFunction<A[]> generator);
> ```

Though this is a bit moot because `super` is not permitted here, I realised upon reflection that the above is still not type-safe as the generator could still return an array of a narrower sub-type due to array covariance (which in turn could cause `ArrayStoreException`). To make this fully type-safe you'd probably just do something like this:
```java
<A super T> Promise<A[]> toArray(Class<A> elementType);
```

**Comment by bjhargrave** [comment]
`extends T` should be removed. It is a mistake.
