### ISSUE TITLE
[Feature] Type of FeatureExtension

### ISSUE THREAD

**Issue by stbischof** [osgi/osgi#264]
FeatureExtension.class must have a type and corresponding methods

```
JSON ->    String getJSON();
TEXT ->    List<String> getText();
ARTIFACTS ->  List<FeatureArtifact> getArtifacts();;
```

When calling one of the Method on a FeatureExtension with an not matching Type (e.g. getJson() on a Artifacts type)  then `null` should be returned.

At the moment i cant see why `FeatureExtension`s must have a Type.

A FeatureExtension  should be able to use the text, json and artifacts in parallel.

```
{
	"id": "org.acme:acmeapp:2.1.0",

	"extensions": {
		"database-init-extention": {
			"artifacts": [{
				"id": "my:jdbc-driver:1.0.0"
			}],

			"json": {
				"user": "bar",
				"pass": ".secret",
				"url": "url.to.db"
			},

			"text": [
				"create table foo ( a int, b int, c int);",
				"insert into foo (a,b,c) values (1,2,3);"
			]
		}

	}
}
```

----

**Alternatively:**
IF the type is really necessary:
I would suggest to not return `null` but throw an `UnsupportedOperationException`

Then this would be also valid FeatureExtension.
```
{
	"id": "org.acme:acmeapp:2.1.0",

	"extensions": {
		"my-execution1": {
			"type": "json",
			"json": null
		},

		"my-execution2": {
			"type": "json"
		},

		"my-execution3": {} // default type is Artifact
	}
}
```

**Comment by maho7791** [comment]
What about making FeatureExtension an Interface that provides 
```
@ProviderType
public interface FeatureExtension {
 String getType();// instead of the enum
 Object getContent();// replacement for hetText, getJson, getArtifacts
}
```
When we then have Implementations for Text, Json, ArtifactExtensions that implement the FeatureExtension interface these classes can provide their convenient methods like getText(), getJson() or getArtifacts().
```
public class TextExtension implements FeatureExtension {
 String getType() {
    return "text"
  }
  Object getContent() {
    return content;
  }
  String getText() {
    return (String)content;
  }
}
```
That would leave us open to have custom implementations for new/other types, just by inheritance. 

We would not have a problem, with cross-field-restrictions, when its calling getJson() will throw an exception when having am extension instance of type *text*. An *instanceof* could make it type safe.

As default, an implementor of this specification can e.g. register the extensions classes or even extension factories (maybe in the FeatureBuilder) like this:
```
register("text", DefaultTextFeature.class);
register("json", DefaultJsonFeature.class);
register("artifact", DefaultArtifactFeature.class);

```
or
```
registerFactory("text", DefaultTextFeatureFactory.class);
registerFactory("json", DefaultJsonFeatureFeature.class);
registerFactory("artifact", DefaultArtifactFeatureFeature.class);
```
Making these *register* and *registerFactory* public, enables to register custom extensions or substitute extensions. This would make the extension more open for customizations.

**Comment by bjhargrave** [comment]
Fixed
