### ISSUE TITLE
[proposal] standarize providing additional properties to JPA persistence context

### ISSUE THREAD

**Issue by laeubi** [osgi/osgi#279]
I have reported this in the bugzilla (ID 123) once but can't find this anymore (and can't find it in the archive either) I'll try to rephrase it here:

Currently JPA reads the metadata in a static way. This leads to the problem that one either has to hardcode connection information, or create an incomplete unit and handle the life-cycle manually. Both approaches are very inconvenient from a management perspective.

The proposal is to allow integration of JPA with the CM service to dynamically discover and apply configuration changes.

In [Pax JPA](https://github.com/ops4j/org.ops4j.pax.jpa) we have implemented the following approach:

1. For any PU we discoverer /track a corresponding configuration under pid `org.ops4j.pax.jpa.pu.<name of pu>`
2. Whenever the configuration changes it updates the properties and maybe comple/register the services

The code responsible for this [can be found here](https://github.com/ops4j/org.ops4j.pax.jpa/blob/master/pax-jpa/src/main/java/org/ops4j/pax/jpa/impl/tracker/PersistenceBundleTrackerCustomizer.java#L131) as an example.

This is very convenient, simple to implement and uses standard OSGi techniques so I'd like to propose that something similar get standardized in the JPA spec.

**Comment by timothyjward** [comment]
> can you reference some more?
Aries JPA is the reference implementation

>I think having more than one OSGi-JPA service won't work well anyways, 

All OSGi specifications have to deal with situations where multiple implementations are present. DS extenders will only process bundles that are wired to their `osgi.extender` capability for this reason.

>and there are other services that mandate how to provide configuration in an provider independent way (e.g. declarative services) so what makes Jpa-Service special here?

No specification of which I am aware standardises a PID. Some standardise framework properties that can be used as defaults, but in those cases the provider-specific configuration takes precedence.

**Comment by laeubi** [comment]
> But it should be rare to have multiple log implementations.

The same applies to JPA (and DS) as well, I really can't think about a use-case where this becomes necessary to have multiple of this services (even though its possible) and in such special configuration one has to make sure that the config binds to the desired implementation (or they can even share the configuration).

**Comment by laeubi** [comment]
Still the most useful feature of PAX JPA, hardcoding values in xml files is just not an option...
