### ISSUE TITLE
[proposal] Add multitenancy support EntityManagerFactoryBuilder

### ISSUE THREAD

**Issue by laeubi** [osgi/osgi#280]
Currently per spec there could only be multiple `EntityManagerFactory`'s created with 'compatible' properties.
In an application it might still be useful to connect e.g. different databases/schemas/...

Eclipse Link (and probably others) have a[ concept of multitenancy](https://www.eclipse.org/eclipselink/documentation/2.5/solutions/multitenancy.htm) where one can provide a property to the connection to choose e.g. different settings per tenant but still usign the same persitence-unit.

The proposal is that the JPA spec also support such isolation e.g. with a property passed to the `EntityManagerFactory#createEntityManagerFactory` method that creates such a context even if a PU with that name already exits. This could then be used to pass provider specific properties alongside with this properties to use such features provided by EclipseLink.

For example we can think of an `osgi.unit.tenant` property that is registered alongside with the usual `osgi.unit.name`, `osgi.unit.version` and `osgi.unit.provider` that allows a consumer to further filter the services watching for when this new feature is present.

**Comment by laeubi** [comment]
In the light of https://github.com/osgi/osgi/issues/279 this could even be enhanced that instead listening to a single configuration an implementation could listen for factory-pids and create one service for each pid similar to how DS behaves to create an instance per configuration.
Then even complex deployments would be possible with JPA Spec (e.g. one could have a discovery that listens for database servers, register a configuration for each of them and then automatically corresponding EntityManagerFactory are available).

**Comment by timothyjward** [comment]
> Eclipse Link (and probably others)

In my experience this isn't the case. The persistence unit name is used as a key by many providers, and therefore having multiple EMFs with different configurations would be a non-starter. One of the key tenets of the OSGi "access" specifications for things like JPA was that it should work entirely within the Java EE specification it was providing access to, otherwise all sorts of provider specific behaviour can end up being required.

**Comment by laeubi** [comment]
Hibernate has also  multitenancy support https://docs.jboss.org/hibernate/orm/4.3/devguide/en-US/html/ch16.html
From my testing neither eclipse-link nor hibernate refuses to create multiple context for the same persistence unit.

**Comment by laeubi** [comment]
Still required.
