### ISSUE TITLE
[Typed Event] TCK Missing coverage areas

### ISSUE THREAD

**Issue by timothyjward** [osgi/osgi#322]
- [x] No test DTOs have nested data (157.2.1.1) 
- [x] No checking of nested data in untyped DTOs (157.2.2) 
- [x] No use of auto-generated topics in delivery (157.3)
- [x] No use of conversion to reified type in a TypedEventHandler (157.4.1)
- [x] No use of service properties to override reified types in a TypedEventHandler (157.4.1)
- [x] No use of event filters (157.4.5) 
- [x] No tests of handler error states (157.4.8) 
- [x] No tests for the Event Monitor service (157.6) 
- [x] No check for the spec mandated capabilities (157.7)

**Comment by stbischof** [comment]
I have a view on this and some more tests that uses the pattern like your tests.

https://github.com/apache/aries-typedevent/blob/main/org.apache.aries.typedevent.bus/src/test/java/org/apache/aries/typedevent/bus/osgi/EventDeliveryIntegrationTest.java#L108

Waiting to get Mockito in with the TCK for the features.

**Comment by timothyjward** [comment]
The Typed Events TCK now has good coverage of the specification
