### ISSUE TITLE
Add SAAJ API contract definition 

### ISSUE THREAD

**Issue by lukasj** [osgi/osgi#330]
https://docs.osgi.org/reference/portable-java-contracts.html#java-ee-contracts defines Java EE contracts. SAAJ API, package `javax.xml.soap`, defined by JSR-67 and available in Java EE is missing there

**Comment by rotty3000** [comment]
also, maybe we could move the issue to that repo. then we can close this one?

**Comment by bjhargrave** [comment]
I asked @lukasj to open the issue here. I would like to keep all the issues for the OSGi spec project in this repo.

Obviously PRs to change the docs need to be in the docs repo.

**Comment by bjhargrave** [comment]
@rotty3000 Can you make a PR for this? I am not sure what SAAJ is and where to find its API?

**Comment by poolborges** [comment]
### SOAP with Attachments API for Java (SAAJ)

`"The initial API was part of JAXM 1.0 in JSR-67 and was released in December 2001; the specification was later separated from JAXM in a maintenance release in June 2002."`

SAAJ is a standard Java API to produce and consume messages conforming SOAP specifications (SOAP 1.1, SOAP 1.2, SOAP Attachment Feature)


### Propose Contract definition

* Contract: JavaSAAJ
* Version: 1.4 
* JSR: 067 
* Java SE Level: 6/7/8/9
* Java EE Level: 8
* Packages:  javax.xml.soap
* Comments: Compatible with 1.3

### JSR-067 Maintenance Release (JSR-067 MR) - Resume

* JSR-067(MR1) - Maintenance revision of the JavaTM API for XML Messaging, version 1.1.
** Define SAAJ as a standalone technology
** https://jcp.org/aboutJava/communityprocess/maintenance/jsr067/jaxm-changelog-accepted.html
* JSR-067(MR2) - Maintenance revision of the SOAP with Attachments API for JavaTM (SAAJ), version 1.2. 
** provide support for the proposed WS-I Basic Profile of SOAP 1.1.
** https://jcp.org/aboutJava/communityprocess/maintenance/jsr067/SAAJ1_2ChangeLogFinal1.html
* JSR-067(MR3) - Maintenance revision of the SOAP with Attachments API for JavaTM (SAAJ), version 1.3 
** provide support for SOAP version 1.2 Message Constructs
** The proposed API changes in SAAJ 1.3 are backward compatible with SAAJ 1.2 APIs.
** https://jcp.org/aboutJava/communityprocess/maintenance/jsr067/SAAJ1_3ChangeLog.html
* JSR-067(MR5) - "same as" JSR-067(MR3)
** https://jcp.org/aboutJava/communityprocess/maintenance/jsr067/SAAJ1_3ChangeLog_4.html
* JSR-067(MR5) - Maintenance revision of the SOAP with Attachments API for JavaTM (SAAJ), version 1.4
** define JDK 9 module for the SAAJ API to be 'java.xml.soap'
** __SAAJ API 1.4 will be the last maintenance release of the JSR 67 specification as a standalone technology__
** __SAAJ API will continue to be released with the Java API for XML-Based Web Services (JAX-WS) 2.0 JSR__
** https://jcp.org/aboutJava/communityprocess/maintenance/jsr067/ChangeLog-SAAJ-1.4-MR.txt


### References

JSR and EE4J
* API - https://github.com/eclipse-ee4j/saaj-api
* RI - https://github.com/eclipse-ee4j/metro-saaj
* JSR67 - https://www.jcp.org/en/jsr/detail?id=67
* JSR67(MR 4) - https://jcp.org/aboutJava/communityprocess/mrel/jsr067/index4.html

SOAP 1.2 Attachment Feature (SOAP-AF)
* https://www.w3.org/TR/soap12-af
* https://www.w3.org/TR/2002/WD-soap12-af-20020924/

JavaEE 8 and JakartaEE 8
* https://jakarta.ee/specifications/platform/8/platform-spec-8.html
* https://www.oracle.com/java/technologies/javaee/javaeetechnologies.html

Tutorial
* https://www.infoworld.com/article/3227793/web-services-in-java-se-part-4-soap-with-attachments-api-for-java.html
* https://docs.oracle.com/javaee/5/tutorial/doc/bnbhf.html

**Comment by rotty3000** [comment]
Thanks, this is helpful.

I'll make the changes in the next few days.

Cheers

**Comment by rotty3000** [comment]
@lukasj @poolborges could you confirm that I've got this correct (just the last commit)?

**Comment by lukasj** [comment]
Yes, that's correct (careful reader may say that older releases are compatible with SE 5 and were for a long time but given where we are, saying 6 as the minimum is fine from my point of view)

**Comment by poolborges** [comment]
> @lukasj @poolborges could you confirm that I've got this correct (just the last commit)?

Yes, is correct.
