### ISSUE TITLE
[proposal] Enhance org.osgi.service.url to support authentication

### ISSUE THREAD

**Issue by laeubi** [osgi/osgi#346]
Currently there is no "OSGi-way" to support authentications. Similar to the URL StreamHandler there is only one static `java.net.Authenticator.setDefault(...)`.

My proposal is to support a new service interface `PasswordAuthenticationProvider` that allows registration of handlers that can provide username/passwords:

```
package org.osgi.service.url.authentication;

import java.net.Authenticator;
import java.net.Authenticator.RequestorType;
import java.net.InetAddress;
import java.net.PasswordAuthentication;
import java.net.URL;

public interface PasswordAuthenticationProvider {

    /**
     * Called when password authorization is needed.
     * 
     * @see {@link Authenticator}
     * @param requestingProtocol
     *            the protocol that's requesting the connection. Often this will
     *            be based on a URL, but in a future JDK it could be, for
     *            example, "SOCKS" for a password-protected SOCKS5 firewall.
     * @param requestingHost
     *            the hostname of the connection requiring authentication, or
     *            null if it's not available.
     * @param requestingSite
     *            the InetAddress of the site requesting authorization, or null
     *            if it's not available.
     * @param requestingPort
     *            an <code>int</code> indicating the port for the requested
     *            connection.
     * @param requestingPrompt
     *            the prompt string given by the requestor (realm for http
     *            requests)
     * @param requestingScheme
     *            the scheme of the requestor (the HTTP scheme for an HTTP
     *            firewall, for example).
     * @param requestingURL
     *            the URL that resulted in this request for authentication.
     * @param requestorType
     *            whether the requestor is a Proxy or a Server.
     * @return The PasswordAuthentication, or <code>null</code> if none is
     *         provided.
     */
    PasswordAuthentication getPasswordAuthentication(String requestingProtocol, String requestingHost, InetAddress requestingSite, int requestingPort,
            String requestingPrompt, String requestingScheme, URL requestingURL, RequestorType requestorType);

}
```

a framework supporting this can the set the default authenticatior collect all `PasswordAuthenticationProvider`s and iterate over them:

```
import java.net.Authenticator;
import java.net.InetAddress;
import java.net.PasswordAuthentication;
import java.net.URL;
import java.util.ArrayList;
import java.util.Collection;

import org.osgi.service.url.authentication.PasswordAuthenticationProvider;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class AuthenticatorProxy extends Authenticator {

    private final Collection<PasswordAuthenticationProvider> authenticators = new CopyOnWriteArrayList<PasswordAuthenticationProvider>();

    public void start() {
        Authenticator.setDefault(this);
    }

    public void stop() {
        Authenticator.setDefault(null);
    }

    @Override
    protected PasswordAuthentication getPasswordAuthentication() {
        String protocol = getRequestingProtocol();
        String host = getRequestingHost();
        InetAddress site = getRequestingSite();
        int port = getRequestingPort();
        String prompt = getRequestingPrompt();
        String scheme = getRequestingScheme();
        URL url = getRequestingURL();
        RequestorType type = getRequestorType();
        for (PasswordAuthenticationProvider a : authenticators) {
            try {
                PasswordAuthentication auth = a.getPasswordAuthentication(protocol, host, site, port, prompt, scheme, url, type);
                if (auth != null) {
                    return auth;
                }
            } catch (RuntimeException e) {
               // ... send framework event ...
            }
        }
        return null;
    }

    public void addAuthenticator(PasswordAuthenticationProvider authenticator) {
            authenticators.add(authenticator);
    }

    public void removeAuthenticator(PasswordAuthenticationProvider authenticator) {
            authenticators.add(authenticator);
    }
}
```

**Comment by tjwatson** [comment]
I would not recommend we place this in the Core Framework.  Instead it should be a separate specification on top of Core.

**Comment by laeubi** [comment]
I just found this close related to the [URL Handlers Service Specification](http://docs.osgi.org/specification/osgi.core/7.0.0/service.url.html) but a separate specification would be good as well.

**Comment by tjwatson** [comment]
The URL handlers have a unique issue because they are singletons and once set they cannot be unset, even by the framework itself without using deep reflection on the java.net package.  This is one reason that the URL handler stuff is a core service because a bundle being started/stopped would have a hard cooping with re-initializing the handlers.  That and the specification wants the bundle URLs to use a framework specific protocol which also requires the URL handlers.

`java.net.Authenticator.setDefault(Authenticator)` doesn't have the same issue.  It allows anyone to blow away the current one or set it to null (assuming they have permission).  I find that a bit odd, but it does mean this can be done on top of the framework instead of building it into all framework instances.

**Comment by laeubi** [comment]
> I find that a bit odd, but it does mean this can be done on top of the framework instead of building it into all framework instances.

That would be fine I think. In fact I have already one bundle providing that "service" and found it very useful so I think it could be useful to become officially supported. I even would contribute my current solution under whatever license is required to be suitable for an OSGi spec.

**Comment by bjhargrave** [comment]
> I even would contribute my current solution under whatever license is required to be suitable for an OSGi spec.

See <https://github.com/osgi/osgi/blob/main/CONTRIBUTING.md#contribution-guidelines> for the process about creating a new OSGi spec (or making a substantial update to an existing OSGi spec).

**Comment by laeubi** [comment]
Still an issue, e.g P2/ECF currently "blows away" the authenticator so one has only the choice to hope no one else has already a need for it.
