### ISSUE TITLE
[proposal] Log Service to use CharSequence

### ISSUE THREAD

**Issue by kriegfrj** [osgi/osgi#370]
I've been using the log service a bit recently, and I've noticed a pattern that frequently emerges that we

Usually when logging you want to build up a useful string to output into the log comprised of the useful information. `StringBuilder` is perfect and typically used for this purpose.

However, the log service takes a `String` as its parameter. Therefore, once you've finished constructing your `StringBuilder`, it is always necessary to convert it to a `String` before handing off for logging. This would typically involves duplicating the entire from the mutable `StringBuilder` to an immutable `String`.

Perhaps we should consider amending the spec for the log interface to add log methods that take a `CharSequence` as a parameter instead of a `String`. That way the client could pass in their `StringBuilder` directly (or indeed, any other method they have chosen to create their char sequence) and avoid the overhead of that final conversion to a `String`.

This could easily be added in a backward-compatible manner through the use of `default` implementations that hand off to the `String` implementation by calling `toString()` on the passed-in message. Of course such a default implementation would not offer any performance advantages - we'd also need to get the implementors on-board. But I think by updating the spec we at least make this a future possibility.

Thoughts?

**Comment by bjhargrave** [comment]
> However, the log service takes a `String` as its parameter.

Are you looking at the [latest log service spec from Core R8](https://docs.osgi.org/specification/osgi.core/8.0.0/service.log.html#d0e54108)? The `LogService` type has been deprecated and replaced by [`Logger`](https://github.com/osgi/osgi/blob/r8-core-final/org.osgi.service.log/src/org/osgi/service/log/Logger.java) which has SLF4J-like logging methods which can of course take `CharSequence` arguments.

So I think what you ask for is already the case.
