### ISSUE TITLE
[service loader mediator] support for prototype scope

### ISSUE THREAD

**Issue by bjhargrave** [osgi/osgi#38]
Original bug ID: [BZ#3088](https://osgi.org/members/bugzilla/show_bug.cgi?id=3088)
From: @rotty3000
Reported version: R7

**Comment by bjhargrave** [comment]
@rotty3000 @bosschaert What do we want to do here?

**Comment by rotty3000** [comment]
The implementation already supports this by specifying a service property `service.scope=prototype` on the capability, so maybe there is no spec change needed.
