### ISSUE TITLE
Update Http Whiteboard Spec for Jakarta EE 9

### ISSUE THREAD

**Issue by cziegeler** [osgi/osgi#381]
As discussed in #54 we want to update the Http Whiteboard specification to Jakarta EE 9. The updated specification should be Jakarta EE 9 only (and not mix with earlier EE versions) - the specification will only use jakarta.servlet packages and not refer to javax.servlet packages.
At the same time, the specification must allow implementations to implement the R7 spec in combination with this new spec.

The new spec should:

- Use a new package (or two new packages) to host the updated o.o.s.http.context and o.o.s.http.whiteboard packages. The services ServletContextHelper and Preprocessor need to be updated to jakarta.servlet packages. 
- o.o.s.http.whiteboard.annotations - update to 2.0 - the consequence is that bundles can't mix old and new services - which should be ok
- o.o.s.http.whiteboard.propertypes - update to 2.0 - the consequence is that bundles can't mix old and new services - which should be ok
- o.o.s.http.runtime and o.o.s.http.runtime.dto - except for the javadoc, these packages do not use javax packages. We could just adjust the javadocs to remove mentioning of package names and make it agnostic. The advantage is that we do not change the major version without a reason and it would allow an implementation to support the new spec as well as the old spec in a single implementation bundle, e.g. by creating jakarta package based proxies for each javax object.

Additional note: an implementation should also still be able to implement the old http service spec in additition.

At least the two open source servlet engine implementations, Eclipse Jetty and Apache Tomcat, require Java 11 as the base. We probably want to base the updated specification on a higher version than Java 8. Therefore we should pick the next LTS version, which is Java 11.

**Comment by stbischof** [comment]
I tryied to asked this i the last call but could not remember the answers correctly. 

When looking an campatible librarys i saw that jetty with Jakarta namespace exists only in Jetty11. But this needs in minimum a jvm11.

https://www.eclipse.org/jetty/download.php

**Comment by cziegeler** [comment]
I've experienced with different variations and this is my proposal:

- http whiteboard specification is updated to version 2
- javax.servlet is replaced everywhere with jakarta.servlet
- New java package o.o.s.h.whiteboard.extensions (we can discuss the name separately) with the *services* from o.o.s.h.context and o.o.s.h.whiteboard
- package o.o.s.h.whiteboard contains only the HttpWhiteboardConstants class and is updated to version 2.0 (we might want to also move this to the new package)
- package o.o.s.h.runtime and package o.o.s.h.runtime.dto only get a minor version update ; the only change are javadoc updates
- The annotation packages  o.o.s.h.w.annotations and  o.o.s.h.w.propertytypes get a version update to 2.0; although the only change are javadoc updates

With this we have a clear cut and a clean 2.0 specification - but on the other hand, implementations can implement version 1.x and 2.0 at the same time as well as the old/outdated http service. And a shared runtime service provides an overview over the whole http service.

This approach can be seen here: https://github.com/cziegeler/osgi/tree/main/org.osgi.service.http.whiteboard/src/org/osgi/service/http

**Comment by bjhargrave** [comment]
Also need to support new Servlet features since Servlet 3.1 (current base) to Jakarta Servlet 5.0 in Jakarta EE 9.

Preprocessor should change to no longer extend Filter. Just be a clone. 

OSGi specs which move to support Jakarta API should still target Java 8 in their API and TCK, but the TCK execution can run on Java 11 (or later) to enable compatible implementations which themselves require Java 11 (or later).

Naming suggestion: org.osgi.service.http => org.osgi.service.servlet.

**Comment by cziegeler** [comment]
Based on our discussion I created a draft api version at : https://github.com/osgi/osgi/tree/design/381/org.osgi.service.servlet.whiteboard

All packages are below the new root org/osgi.service.servlet/whiteboard and as this is a major update of the specification, I started with 2.0 version for all packages.

We need to decide whether we want the runtime packages next to the whiteboard package (like we had in the existing spec) or below whiteboard (like in my draft).

I didn't change Preprocessor - I remember now that we had a long discussion about it and then decided that "if something looks like a filter and behaves like a filter, it should be a filter" and then went with the marker interface approach. 

While I like the new package names, it feels a little bit clumsy that the package says "Servlet Whiteboard" while everything else (class names, fields, constants etc) says "Http Whiteboard". But to make code migrations easier, we shouldnt change those parts.

I looked into servlet 4.0/5.0 and I think there is nothing new compared to 3.1 (current base) which we need to explicitely mention/support.

We probably need to create new contracts for "JakartaServlet" (see #124 )

**Comment by grgrzybek** [comment]
@cziegeler 
> I looked into servlet 4.0/5.0 and I think there is nothing new compared to 3.1 (current base) which we need to explicitely mention/support.

The one addition compared to 3.1 is the Push API:
```java
javax.servlet.http.PushBuilder builder = req.newPushBuilder();
if (builder != null) {
	// can be null on Jetty
	builder.path("servlet/default.css").push();
	builder.path("servlet/app.js").push();
}
```

I'm working on Pax Web project and recently we've released version 8.0.1. It should be (I didn't check the TCK yet...) almost compatible with CMPN R7/R8 specs (with one explicit violation, which is irrelevant here).
I can test Pax Web with the new 102/128/140 specifications soon(ish).

For a while I was thinking that `org.osgi.service.http.HttpService` could be extended to add jakarta-aware methods in addition to javax ones. But it was a silly idea.
I have a little schadenfreude feeling remembering the discussions back in ~2005+ that JavaEE is safe and Spring is proprietary and we should all rely on JavaEE...

Now we're in the state of emergency, as there's no deprecation period, no slow deprecation+removal transition of the interfaces. It has to be one slash, after which _everything_ has to be jakarta.* based. I'm not considering the bytecode manipulation a clean approach, so I'll skip it.

Pax Web 8 has lots of integration tests (Whiteboard, HttpService and Web Applications specs) involving 3 runtimes (Jetty/Tomcat/Undertow) and different web technologies (JSF/MyFaces/Primefaces, CDI/Weld-Web, JSP, Spring Web, HTTP/2, WebSockets) and several things not mentioned in CMPN (welcome files, SCIs, Login Configuration). And to be honest, I'm a bit overwhelmed trying to count the things that should be checked to get the same state as with JavaEE/JakartaEE 8 (javax packages)...

**Comment by cziegeler** [comment]
Thanks @grgrzybek  - yes PushBuilder is new, but I expect it to just work and we don't need anything additional in the spec to make it work. For HttpService, I think the whiteboard will cover all those use cases. In addition, at least for the Apache Felix implementation I plan to provide an implementation that supports Http Service (javax.servlet), the javax.servlet based Whiteboard and the jakarta.servlet based whiteboard. Even allowing to mix and match. This will at least OSGi applications/bundles to slowly migrate in terms of http - the all or nothing approach requiring all code to be updated is not going to fly in reality and I want to stay away from bytecode manipulation as well.

As we are updating the http whiteboard spec, if you think that anything is missing there this is a good time to bring it up.

**Comment by grgrzybek** [comment]
I'll clone https://github.com/osgi/osgi/tree/design/381/org.osgi.service.servlet.whiteboard and play with it for a while. I wanted to test Pax Web 8 with Jetty 10 and I can do the same with Tomcat 10 / Jetty 11 as well. At quick glance, I don't think anything is missing, however I was confused by the `org.osgi.service.http` → `org.osgi.service.servlet` rename.

**Comment by bjhargrave** [comment]
We discuss the proposal in the branch in the spec call today. It looks good. We had a couple of comments.

1. ServletContextHelper should be moved into a context sub-package of whiteboard (similar to how it is in a context sub-package in the current Http Whiteboard spec).
2. The branch should also include the removal of the old org.osgi.service.http.whiteboard projects and other changes related to the replacement by the new org.osgi.service.servlet.whiteboard package.

**Comment by cziegeler** [comment]
Due to rebasing problems I moved the code to a new branch https://github.com/osgi/osgi/tree/design/381-clean

Created a PR
https://github.com/osgi/osgi/pull/490

**Comment by cziegeler** [comment]
The code base has been updated accordingly, all tests are in place (with the same coverage as previously for the http whiteboard specification), spec chapter builds fine.
A release candidate of the API 2.0.0-RC1 has been released. I've updated the implementation in Apache Felix to use this api and started the release vote.

**Comment by stbischof** [comment]
Pleas look at

```
<dependency>
    <groupId>org.apache.felix</groupId>
    <artifactId>org.apache.felix.http.jetty12</artifactId>
    <version>1.1.0</version>
</dependency>
```


Or

https://github.com/apache/felix-dev/blob/master/http%2FREADME.md
