### ISSUE TITLE
Update JAX-RS Whiteboard Spec

### ISSUE THREAD

**Issue by timothyjward** [osgi/osgi#385]
Thoughts so far:

* Jakarta namespace changes
    - Whiteboard service types should be a simple change
    - Injection of underlying types is harder (e.g. `@Context HttpServletRequest`). Do we require that the whiteboard run on a jakarta servlet container?
* Minor spec updates
    - `osgi.jaxrs.application.select` is defined as a `String` but should be a `String+` like the extension select property

I'm sure that there will be other things to add. This bug is to help collect comments.

**Comment by maho7791** [comment]
We already have a, JaxRs implementation based on Jersey that not fully passes the TCK yet. So I think there is already a Jersey based on the jakarta namespace. If the timeline is not to hard we, can imagine to update our Jersey implementation and make it pass the TCK.

**Comment by timothyjward** [comment]
Having left this to settle for a while, and looking at what is happening in similar specifications (HTTP whiteboard), I think that we have the following changes:

1. Rename the specification to the Jakarta RESTful Web Services Whiteboard to match [the new Jakarta name](https://jakarta.ee/specifications/restful-ws/)

2. Rename the `org.osgi.service.jaxrs.*` packages to `org.osgi.service.jakartars.*`, and whiteboard API types with names starting `Jaxrs...` become `JakartaRs...`

3. Applicable annotation/extension packages for the whiteboard are moved from `javax.ws.rs` to `jakarta.ws.rs.*`, and context injection for Servlet types into Jakarta-RS types (if supported) will be `jakarta.servlet.*`.

4. The service properties relevant to the whiteboard will be renamed from `osgi.jaxrs.*` to `osgi.jakartars.*`

5. The name of the wihteboard implementation will change from `osgi.jaxrs` to `osgi.jakartars`

6. The minor update to the application selection filter (making it String+) will be applied 


This approach will allow implementations to simultaneously support both old and new API versions (if they wish), and the change in service property names will ensure that the whiteboard can understand whether to introspect for old or new versions of annotations. 

Applications will need to be updated to use the new properties, but as they would already require updating to use the new Jakarta packages this is not seen as a significant hurdle.

Assuming that people are happy with this then I am happy to begin a PR updating the specification and interfaces. @bjhargrave @maho7791 @rotty3000 @juergen-albert?

**Comment by rotty3000** [comment]
Sounds reasonable!

**Comment by bjhargrave** [comment]
This sounds fine. I assume this change will depend upon the changes to http whiteboard?

**Comment by timothyjward** [comment]
> I assume this change will depend upon the changes to http whiteboard?

I'm not certain that this change does have a strict dependency on the HTTP whiteboard changes. The Jakarta and OSGi specifications for this don't have any hard links to the Servlet or HTTP whiteboard specifications (only a soft dependency on being able to `@Context` inject the `HttpServletRequest` if one is available). It was/is possible to run a JAX-RS runtime without a Servlet Container directly on something like Grizzly/Netty, and I don't think that this has changed in Jakarta. 

Currently neither the OSGi API code nor the `1.0.0` CT have any dependency on the HTTP whiteboard. For practical purposes however, the current RI definitely makes use of the HTTP whiteboard. I'm pretty sure that the Jersey based implementation that @maho7791 mentioned is also using the HTTP whiteboard. We may therefore find that a dependency on the HTTP whiteboard creeps in from that direction.

**Comment by bjhargrave** [comment]
> We may therefore find that a dependency on the HTTP whiteboard creeps in from that direction.

OK, so we won't have a spec dependency, but we will probably have a compatible implementation dependency.

**Comment by maho7791** [comment]
Our Jersey implementation uses the HTTP Whiteboard, but we also have an option not to use it. 
We can use Jersey as plain Servlet, with or without HTTP Whiteboard. 
We usually use Jetty, which already comes with a jakarta version. So I dont see any problems for the moment, from our side

**Comment by bjhargrave** [comment]
We discussed the proposal in the branch in the spec call today. It looks good. We asked for the PR to be moved to a branch which Tim will do.

**Comment by maho7791** [comment]
The latest Gecko REST Jersey Jakartars Whiteboard implementation runs the Jakartars TCK with 53 successful and 4 failing tests.
Sometimes the ClientTestCase#testJaxRsClientService looks flaky, It sometimes returnes a 200 where a 404 should be returned. Obviously a previous jakartars resource wasn't properly removed.
Running this test alone, never showed this behavior.

**Comment by timothyjward** [comment]
The Gecko REST implementation is now passing the whole TCK. I think that PR #417 is now ready to merge into the main branch, and the specification ready to begin the release process.

**Comment by timothyjward** [comment]
Closing as the specification chapter, RI and TCK are all complete
