### ISSUE TITLE
DS 1.5: Clarify sorting order of collections injected with Field Injection and Replace Field Option

### ISSUE THREAD

**Issue by kwin** [osgi/osgi#400]
According to https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.component.html#d0e30610

> Before the component instance is activated, SCR must set the field value with a new mutable collection that must contain the initial set of bound services sorted using the same ordering as ServiceReference.compareTo based upon service ranking and service id. The collection may be empty if the reference has optional cardinality and there are no bound services. If the reference is dynamic, when there is a change in the set of bound services or the service properties of a bound service are modified and the collection holds service properties, SCR must replace the field value with a new mutable collection that must contain the updated set of bound services sorted using the same ordering as ServiceReference.compareTo based upon service ranking and service id. 

It isn't stated whether the collection is sorted ascending or descending based on `ServiceReference.compareTo()`. This should be explicitly mentioned (even if ascending is the natural sorting order). Maybe even an example illustrating that a higher ranked service follows after a lower ranked service in the list would be good (and to explicitly mention that https://docs.osgi.org/javadoc/osgi.core/8.0.0/org/osgi/framework/BundleContext.html#getServiceReference-java.lang.Class-) would return the last item in such a collection.

**Comment by kwin** [comment]
I think in most of the cases a descending order is actually wanted to make it possible that a higher ranked service can override a lower ranked service. Probably that should be mentioned as well.

**Comment by bjhargrave** [comment]
I think [ServiceReference.compareTo](https://docs.osgi.org/specification/osgi.core/8.0.0/framework.api.html#org.osgi.framework.ServiceReference.compareTo-Object-) javadoc is quite clear on the sorting order: lower comes before higher (i.e. ascending). Which is generally how people expect the natural sort order. So I think the ServiceReference.compareTo javadoc is sufficiently clear on this matter.

In general, I don't think specifications should repeat normative information. There should be a single place for the normative information and other areas of the specification can refer to that. Of course, the specification, as a whole, was written over many years, so we sometimes fail to update older areas to refer to more relevant newer areas. I see that the javadoc for BundleContext.getService was not updated to refer to the natural ordering defined in ServiceReference.compareTo.

If you have specific wording changes you think are necessary, please make a PR.

**Comment by tjwatson** [comment]
One area of the spec that lacks any mention of order is [ComponentContext.locateServices](https://docs.osgi.org/javadoc/osgi.cmpn/8.0.0/org/osgi/service/component/ComponentContext.html#locateServices-java.lang.String-)

I think we must mention something here about order.  I think the current compatible implementation (Felix SCR) returns the array in reverse natural order here.

**Comment by kwin** [comment]
Also [BundleContext.getServiceReferences(java.lang.Class<S> clazz, java.lang.String filter)](https://docs.osgi.org/javadoc/osgi.core/8.0.0/org/osgi/framework/BundleContext.html#getServiceReferences-java.lang.Class-java.lang.String-) and  [(java.lang.String clazz, java.lang.String filter)](https://docs.osgi.org/javadoc/osgi.core/8.0.0/org/osgi/framework/BundleContext.html#getServiceReferences-java.lang.String-java.lang.String-) don't specify an order. If the returned order is different from field injection, we should probably point that out in the spec next to enriching the javadoc.

**Comment by bjhargrave** [comment]
OK, I will take an effort to update the locations which are mute on ordering. Note, the update may be to state that no ordering is specified. For example BundleContext.getServiceReferences will likely be updated to state the returned references are not ordered in any way.

**Comment by bjhargrave** [comment]
See PR #401
