### ISSUE TITLE
Create a Service Release of the Converter Util Jar

### ISSUE THREAD

**Issue by bosschaert** [osgi/osgi#402]
The following improvement was made recently to the Converter:

* #392
 
We need a Service Release to allow users to pick up this improvement.

**Comment by bosschaert** [comment]
Associated email thread: https://www.eclipse.org/lists/osgi-dev/msg00074.html

**Comment by bjhargrave** [comment]
I also want to release the updated osgi.annotation jar with the fix: #404. I am thinking it should be version 8.1.0 since the `org.osgi.annotation.bundle` package is updated to version 2.0. I don't think it is time to release a version 9.0.0 yet.

**Comment by bjhargrave** [comment]
Service release has been made. 1.0.9 of the converter jar and 8.1.0 of osgi.annotation are now in maven central.
