### ISSUE TITLE
First Reference link in DS Specifcation is dead

### ISSUE THREAD

**Issue by juergen-albert** [osgi/osgi#422]
```
112.17 References
[1]Automating Service Dependency Management in a Service-Oriented Component ModelHumberto Cervantes, Richard S. Hall, Proceedings of the Sixth Component-Based Software Engineering Workshop, May 2003, pp. 91-96
http://www-adele.imag.fr/Les.Publications/intConferences/CBSE2003Cer.pdf
``` 

The [PDF](http://www-adele.imag.fr/Les.Publications/intConferences/CBSE2003Cer.pdf) is not available anymore under this link. We should either remove it, relink it to its new location or host it ourself if we can dig it up somewhere.

**Comment by pkriens** [comment]
You can use links to archive.org: https://web.archive.org/web/20061123212733/http://www-adele.imag.fr/Les.Publications/intConferences/CBSE2003Cer.pdf
