### ISSUE TITLE
TCK JaxRS Whiteboard SSE Test is not JaxRs Spec compliant

### ISSUE THREAD

**Issue by maho7791** [osgi/osgi#426]
Test:
https://github.com/osgi/osgi/blob/main/org.osgi.test.cases.jaxrs/src/org/osgi/test/cases/jaxrs/junit/SSETestCase.java

The test setup expects that the client stops receiving data, when the server side closes the event sink. According to the JaxRs specification, the server side close is handles as a connection loss. The client has to re-establish the connection. So the setup will:
* receive more than the 10 data elements, because a reconnect happens
* the onComplete that releases the sempahore is not called
I stumbled up that while testing our JaxRs Whiteboard against the TCK with Jersey. 

There is already an issue at Jersey, that describes the problem:
https://github.com/eclipse-ee4j/jersey/issues/4996

**Comment by maho7791** [comment]
See PR https://github.com/osgi/osgi/pull/427

**Comment by timothyjward** [comment]
Fixed by #428
