### ISSUE TITLE
[Converter] Should custom rules/error handlers be applied in reverse order?

### ISSUE THREAD

**Issue by bjhargrave** [osgi/osgi#43]
Original bug ID: [BZ#3106](https://osgi.org/members/bugzilla/show_bug.cgi?id=3106)
From: @bosschaert
Reported version: R7

**Comment by bjhargrave** [comment]
@bosschaert What remains to be done with this issue?

**Comment by bosschaert** [comment]
This was fixed http://svn.apache.org/viewvc?view=revision&revision=1855240
