### ISSUE TITLE
"Usefull Links" are actually not very useful

### ISSUE THREAD

**Issue by laeubi** [osgi/osgi#438]
If I visit https://www.osgi.org/ at the bottom there is a section named "Useful Links", but actually from a non expert eclipse/osgi user these are actually not very useful:

- **Report a Bug** links to https://bugs.eclipse.org/bugs/ beside that bugzilla is about to be shut down a user is most likely confused what all this stuff is about and most probably should better link to github
- **Documentation** links to https://help.eclipse.org/latest/index.jsp it is very unlikely that the eclipse help helps anyone who want to learn more about OSGi, most probably should it link to either the current spec or even better a more user friendly "user-doc" that explain: What is OSGi about, Where can I find some examples, Where can I read the Spec ...
- **How to Contribute** links to https://www.eclipse.org/contribute/ what suggest me to to download the current eclipse I-Build, what most likely is not what user want if they like to contribute to OSGi
- **Mailing Lists** links to https://accounts.eclipse.org/mailing-list and should at least link to the OSGi-WG mailing list to be helful for newcomers.
- **Forums** links to https://www.eclipse.org/forums/ which has no real section about OSGi, and often is a dead end as the user-base is quite low. This might better link to more recent communication channels (Slack?).
- **Marketplace** links to https://marketplace.eclipse.org/ very unlikely I'll find anything useful regarding OSGi there, its completely unclear what this is supposed to do with regard to OSGi.

**Comment by bjhargrave** [comment]
Thanks for the issue, but this is not the correct repo for the www.osgi.org website. Please open this issue in https://gitlab.eclipse.org/eclipsefdn/it/websites/osgi.org. Thanks.

**Comment by laeubi** [comment]
See https://gitlab.eclipse.org/eclipsefdn/it/websites/osgi.org/-/issues/53
