### ISSUE TITLE
"About us" should tell the user more about OSGi and probably the history

### ISSUE THREAD

**Issue by laeubi** [osgi/osgi#439]
From a newcomers perspective the "About us" on https://www.osgi.org/about/ is not very informative.

Given that I want to direct new users to learn something about OSGi they are most probably confused when reading the "About us", e.g. it refers to special terms (TCK??) and even "former OSGi Alliance" but do not give a hint how can one learn about the "former", so just in case a user has have never heard about OSGi, he most probably have no idea what this "former OSGi Alliance" is about.

**Comment by bjhargrave** [comment]
Thanks for the issue, but this is not the correct repo for the www.osgi.org website. Please open this issue in https://gitlab.eclipse.org/eclipsefdn/it/websites/osgi.org. Thanks.

**Comment by laeubi** [comment]
See https://gitlab.eclipse.org/eclipsefdn/it/websites/osgi.org/-/issues/54
