### ISSUE TITLE
Remove the FAQ or fill with actual content

### ISSUE THREAD

**Issue by laeubi** [osgi/osgi#440]
Currently the "FAQ" contains one entry here https://www.osgi.org/about/faq/ "What is OSGi Working Group?" ... and one might wonder whats the difference between "FAQ" and "About".

So if "What is OSGi Working Group?" being the only frequently asked question, it might be better to disable the FAQ and incooperate it into the "About us"

If one really likes to have a FAQ, these questions should be more User centric e.g.:

- What is OSGi about
- Why should I use it
- How do I migrate from ... to OSGi
- ....

**Comment by bjhargrave** [comment]
Thanks for the issue, but this is not the correct repo for the www.osgi.org website. Please open this issue in https://gitlab.eclipse.org/eclipsefdn/it/websites/osgi.org. Thanks.

**Comment by laeubi** [comment]
See https://gitlab.eclipse.org/eclipsefdn/it/websites/osgi.org/-/issues/52
