### ISSUE TITLE
Handle JDBC_PASSWORD property as a secret

### ISSUE THREAD

**Issue by stbischof** [osgi/osgi#446]
The propertY `JDBC_PASSWORD` of a DataSourceFactory is a secret. 
So it might start with a `.` to make ithis property only accessible for the Service itself.

```
	/**
	 * The "password" property that DataSource clients should supply a value for
	 * when calling {@link #createDataSource(Properties)}.
	 */
// OLD
	public static final String	JDBC_PASSWORD				= "password";
	
// NEW
	public static final String	JDBC_PASSWORD				= ".password";
```

**Comment by timothyjward** [comment]
We should not change the value of this constant. It is intended to match the property name used in the JDBC specification, which is `password`.

If someone wants to supply a password to a component in a configuration dictionary then that property should start with a `.` e.g. `.password`, however the JDBC driver should not be expected to understand this additional syntax.
