### ISSUE TITLE
org.osgi.service:org.osgi.service.prefs artifacts relocated to org.osgi groupId

### ISSUE THREAD

**Issue by julien-carsique-sonarsource** [osgi/osgi#447]
It looks like the `org.osgi.service.prefs` artifacts have been moved from `org.osgi.service` to `org.osgi` group. 
https://search.maven.org/artifact/org.osgi/org.osgi.service.prefs
Was it on purpose? If so, relocation POMs are missing at the old locations.

```
Could not resolve dependencies for project ...: Failed to collect dependencies at org.eclipse.jdt:org.eclipse.jdt.core:jar:3.29.0 
-> org.eclipse.platform:org.eclipse.core.resources:jar:3.14.0 
-> org.eclipse.platform:org.eclipse.core.runtime:jar:3.12.0 
-> org.eclipse.platform:org.eclipse.equinox.preferences:jar:3.10.0 
-> org.osgi.service:org.osgi.service.prefs:jar:[1.1.0,1.2.0): 
No versions available for org.osgi.service:org.osgi.service.prefs:jar:[1.1.0,1.2.0) within specified range
```

The issue raised in all our projects this morning (June, 15th, 2022). I worked around internally with two relocations:
- `org.osgi.service:org.osgi.service.prefs:pom:1.1.1` -> `org.osgi` groupId
- `org.osgi.service:org.osgi.service.prefs:pom:1.1.2` -> `org.osgi` groupId

**Comment by juergen-albert** [comment]
Not sure where you have gotten the jar from before, but to my knowledge there never has been a org.osgi.service groupid, we released anything under. https://search.maven.org/search?q=g:org.osgi.service shows that such a group does not exists and thus never has existed on maven central. 

We have always released under the org.osgi groupid.

**Comment by julien-carsique-sonarsource** [comment]
It was not clear to me where was set the groupId looking at the bnd files.
The fact that it raised today can be a cache expiration/cleanup that made our Artifactory download the proper POM versus the one it had in cache...
Then, I'm digging on my side where the wrong GAV comes from and will come back to you.
Thank you

**Comment by bjhargrave** [comment]
POM generation with the groupId `org.osgi` was added to the OSGi build in Nov, 2014. 

https://github.com/osgi/osgi/commit/ff497ca563ccda51a3491ccd8333df384c4afe3d

**Comment by julien-carsique-sonarsource** [comment]
Thank you @PatriceMoreau56 , eclipse-equinox/equinox.bundles#54 is the root cause.
