### ISSUE TITLE
Possible mistake in JaxRs Whiteboard Specification

### ISSUE THREAD

**Issue by maho7791** [osgi/osgi#449]
https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.jaxrs.html#d0e134849

The properties section mentions a property *service.exported.interfaces* as required with description *Set appropriately to export the Endpoint service using OSGi Remote Services.*.

ThIs seems to be an copy and waste mistake.

**Comment by bjhargrave** [comment]
I think we should probably delete the row in the table.

**Comment by bjhargrave** [comment]
Table caption is also wrong.

**Comment by timothyjward** [comment]
> This seems to be an copy and waste mistake.

The intent of this is to require that the JaxrsEndpoint services registered by the implementation are "exportable". Specifically if you have a remote services implementation running then the other frameworks in your system should be able to discover the endpoints provided.

**Comment by maho7791** [comment]
But then we should remove the require tag from the line

**Comment by timothyjward** [comment]
> But then we should remove the require tag from the line

Why? I'm not sure what the disadvantage or overhead is in saying that the implementation must register the service with `service.exported.interfaces=org.osgi.service.jaxrs.runtime.JaxrsEndpoint`

**Comment by maho7791** [comment]
Just to get it right. Every successful registered resource and application must register this service? 

If yes, is that covered by the TCK? I believe not. Because we didnt implemented this in the Jersey Whiteboard 😔. In the end we need to parse the resources and applications for jaxrs annotations as well to get these information as long as jersey does not provide the necessary information.

**Comment by maho7791** [comment]
It seems this also could have been realized using the conditions? So, I would go for the proposed removal.

**Comment by bjhargrave** [comment]
I am ok with removing the reference to remote services.
