### ISSUE TITLE
Core: Clarification on multi-release containers and Bundle.getEntry

### ISSUE THREAD

**Issue by bjhargrave** [osgi/osgi#470]
The Core spec was previously updated to support Multi-Release JARs. 

In the Core spec, the concept of [_containers_](https://docs.osgi.org/specification/osgi.core/8.0.0/framework.module.html#framework.module.bundleclasspath) was defined. 

> JAR, ZIP, directories, etc. are called containers. Containers contain entries organized in hierarchical paths.

Any container can be a [_multi-release container_](https://docs.osgi.org/specification/osgi.core/8.0.0/framework.module.html#framework.module-multireleasecontainer). 

A bundle's Bundle-Classpath is a list of containers, any of which can be a multi-release container, that are searched in the specified order by the bundle's class loader for classes and resources. That is, the class loading support is built on Bundle-Classpath which is then built upon containers. 

The main bundle jar is itself a container and thus can also be a [multi-release container](https://docs.osgi.org/specification/osgi.core/8.0.0/framework.module.html#framework.module-multireleasejar).

Since the main bundle jar is a container of entries, it then follows that locating entries in the bundle, via Bundle.getEntry, should support multi-release. This conclusion would allow DS xml to have different content for different Java versions since DS xml is read from the bundle via Bundle.getEntry.

However, Equinox only supports the multi-release part of containers during class loader lookup. Bundle.getEntry does not respect multi-release.

So we need to either clarify the Core spec that containers do not support multi-release for Bundle.getEntry, or we need to fix Equinox (and possibly Felix) to support multi-release for Bundle.getEntry. TCK updates may also be necessary.

**Comment by tjwatson** [comment]
See https://github.com/osgi/design/blob/main/rfcs/rfc0238/rfc-0238-Multi-Release-Jar-Support.pdf 

```
5.3 Bundle Entries
The framework APIs which provide access to bundle content independent of the bundle class loader, such as
Bundle.getEntry, Bundle.getEntryPaths, Bundle.findEntries, and BundleWiring.findEntries,
are not affected by multi-release JAR support. Multi-release JAR support only affect access to bundle content
through the bundle class loader. That is, class loading and resource loading.
```

I'm pretty sure the TCK has an assertion for this section of the RFC.

**Comment by bjhargrave** [comment]
It is possible this changed post-RFC or the spec writing failed to capture this.

**Comment by tjwatson** [comment]
Perhaps it needs clarification in the specification.  But there are assertions in https://github.com/osgi/osgi/blob/main/org.osgi.test.cases.framework.launch/src/org/osgi/test/cases/framework/launch/junit/MultiReleaseJarTestCase.java that test this.  So all compliant frameworks behave this way.

The term container here is in the context of the class loading section of the spec so I believe the intent of the spec was to only apply MR Jars for class/resource loading from the bundle class loader and not have them apply for access the raw entries of the actual bundle file.

**Comment by bjhargrave** [comment]
Call: Update Core spec to make clear getEntry does not participate in multi-release shenanigans. Update DS spec to discuss multi-release: tools are not required to process version folders, component impl class should not be versioned and should instead depend upon a versioned helper class if necessary.
