### ISSUE TITLE
Need CM compatible implementation update for TCK change

### ISSUE THREAD

**Issue by bjhargrave** [osgi/osgi#474]
Related Issue in Felix-Jira: https://issues.apache.org/jira/browse/FELIX-6470

_Originally posted by @stbischof in https://github.com/osgi/osgi/issues/343#issuecomment-1163116780_

**Comment by cziegeler** [comment]
This case actually raises an interesting question about how notifications happen when the coordination finishes.
Simplified use case: managed service is registered, it gets updated with null. Now a coordination starts, a configuration is created, and then deleted before the coordination finishes. The coordination then finishes. Is the managed service notified at all as the state before the coordination and after the coordination is the same?
The specification is open about this, but my interpretation is that it is ok for the CM implementation to not send notifications in such a case, as they would only cause unnecessary churn.
If we follow that thought, then we could say that the notifications that are send out after the coordination finishes "report" the diff between the state before the coordination started and after. For example, if a configuration is updated several times throughout a coordination, only one notification is send out with the latest configuration.

**Comment by bjhargrave** [comment]
For coordinations, the goal is to avoid observing intermediate states. So when the coordination ends, CM must only notify with the final config state. So this means the CM impl should be able to collapse multiple changes to a config during a coordination to a single notification. 

Given this, both the TCK tests for coordination and the impl need to change.

**Comment by stbischof** [comment]
I take the tck part.

**Comment by cziegeler** [comment]
@stbischof  I just updated the implementation in Apache Felix. There, I added these tests: https://github.com/apache/felix-dev/blob/master/configadmin/src/test/java/org/apache/felix/cm/integration/CoordinatorIntegrationTest.java
