### ISSUE TITLE
Define `deprecated` directive for capabilities

### ISSUE THREAD

**Issue by bjhargrave** [osgi/osgi#509]
Things get deprecated over time and Java has a deprecation annotation and javadoc tag to produce warnings for users during compilation.

But we currently have no defined way for a capability to declare itself deprecated. [For example](https://github.com/eclipse-equinox/equinox/issues/18), refactoring of a product could lead to a situation where a bundle is hollowed out and other bundles should stop requiring it using Require-Bundle. With a deprecation directive, the shell bundle could declare itself deprecated:

```
Bundle-SymbolicName: foo.bundle;deprecated:="This bundle is deprecated. Please use Import-Package to access any packages this bundle re-exports."
```

Packages may also want to declare themselves deprecated.

```
Export-Package: foo.package;deprecated:="This package is deprecated and has been replaced by foo.acme.package."
```

Tooling could then provide deprecation warnings to developers when they use a capability that has been marked deprecated. Resolver hooks could use the deprecation information to report on the use of deprecated capabilities in a resolution. 

We may also want to add a `deprecated` element to the `Export` annotation to allow defining the deprecation information in the `package-info.java` source file. (Unfortunately, the obvious idea to just use the existing `Deprecated` annotation in a `package-info.java` file results in a compiler warning that cannot be suppressed: `warning: [deprecation] @Deprecated annotation has no effect on this package declaration`.)

**Comment by laeubi** [comment]
Just wondering, but defining such think "only" would make it official so something like this is already legal?

**Comment by bjhargrave** [comment]
It would be a good practice to define custom directives in an OSGi specified namespace with some prefix like `x-`. But in this case, since OSGi is proposing a new directive, using the proposed new directive in Equinox should be fine as it gives some use experience.

The OSGi specifications require the ignoring of unknown directives, so it is safe to add this. For a `deprecated` directive, I would expect it to be ignored at runtime by the OSGi framework (other than perhaps to report in the use of deprecated capabilities). The directive is more useful prior to runtime when developing and assembling bundles.

**Comment by tjwatson** [comment]
Adding the directive looks to be pretty straight forward.  Before adopting the use of it I would like agreement on the value of the directive.  The suggestion is the value will be some human readable message.  Then tools can use that message to provide warnings to the user during bundle development/build time.  That seems reasonable to me, but it has the limitation of not being translatable.  We have translatable manifest headers, but that is to translate the complete header and we don't allow capability specifying headers (i.e. Provide-Capability, Export-Package etc) to be translated like other headers (i.e. Bundle-Description).

My preference is to state that such deprecated values cannot be translated, but that may be unfair given that English is my first language.

**Comment by bjhargrave** [comment]
Directive values are always String. So we know the type of the value.

The question is what does the string value mean? I assume it is like the value in the javadoc deprecated tag: `@deprecated "some deprecation message"`. That is, it is for developers and not end users. So the value is not meant for i18n.

**Comment by tjwatson** [comment]
> That is, it is for developers and not end users. So the value is not meant for i18n.

That is fine with me.

> @tjwatson why not use the usual translation feature that is adding a `%<my default message>`?

Because we don't allow directives to be translated today, so that is new and makes it more complicated.

My vote is to make it clear that the value is not meant for i18n.

**Comment by bjhargrave** [comment]
> I think one _might_ want to emit a warning on the LogService at the discretion of the Framework implementation as well, e.g. Java already warns you at runtime if you use features from the JDK that are likely to vanish (at least once for a JVM session).

Sure, that is a fine implementation choice for a framework implementation. But the OSGi spec will not specify that.

**Comment by HannesWell** [comment]
This proposal is really a missing piece in OSGi that I would find useful, I already wonder in the past how bundle/package level deprecation should be expressed in a technical way (besides announcing it somewhere). 

> 
> The question is what does the string value mean? I assume it is like the value in the javadoc deprecated tag: `@deprecated "some deprecation message"`. That is, it is for developers and not end users. So the value is not meant for i18n.

I agree on this for the reason Christoph mentioned.

And looking at the `@java.lang.Deprecated` annotation, I wonder if it would be useful to have a `since` and `forRemoval` value as well. But not sure how to implement that in a elegant way since (as far as I now) directives only have an argument but not further 'children'. If that seems necessary, a simple way would be do add a `deprecated-since` and `deprecated-forRemoval` directive as well (that is only considered/allowed if the deprecated directive is present?).

**Comment by bjhargrave** [comment]
> a simple way would be do add a `deprecated-since` and `deprecated-forRemoval` directive as well (that is only considered/allowed if the `deprecated` directive is present?).

That is getting too complex. 

I think the model is the javadoc `@deprecated` tag and not the `@Deprecated` annotation. The string value can contain any since information and removal plans as well as, to me the most important thing which is missing from the `@Deprecated` annotation, what does the developer need to do to replace the deprecated usage.

**Comment by HannesWell** [comment]
> > a simple way would be do add a `deprecated-since` and `deprecated-forRemoval` directive as well (that is only considered/allowed if the `deprecated` directive is present?).
> 
> That is getting too complex.

Agree. I already thought that it is definitely not elegant.

> 
> I think the model is the javadoc `@deprecated` tag and not the `@Deprecated` annotation. The string value can contain any since information and removal plans as well as, to me the most important thing which is missing from the `@Deprecated` annotation, what does the developer need to do to replace the deprecated usage.

That's definitely the most interesting thing since whatever is deprecated should not be used regardless of if and when it will be removed. I mainly just wanted to mention those aspects and maybe it would be useful to make suggestions/examples in the spec that it could be done the way you suggested, if somebody really wants to add those information.

**Comment by laeubi** [comment]
I must confess that for me any deprecated stuff is something I should get rid of. This "for removal" is just a hack, because Java deprecated stuff but never removed it (so people just ignored that) and need a way to say "this is REALLY deprecated" ...

**Comment by HannesWell** [comment]
In https://github.com/eclipse-equinox/equinox/issues/18#issuecomment-1864616264 @tjwatson mentioned that there could be advantages in defining the deprecation as attribute to allow filtering.
Tom do you think the question attribute vs. directive should be rethought or do you think that if generally applied (not only for packages but also for exported packages or general capabilities) it is best to stick with directives?
