### ISSUE TITLE
[tck][jdbc] 125.2.1 Life Cycle is not covered by the TCK

### ISSUE THREAD

**Issue by laeubi** [osgi/osgi#533]
> A Data Source Factory service should be registered while its Driver Bundle is in the ACTIVE state or when it has a lazy activation policy and is in the STARTING state. 

Currently there is no test that checks that actually this "Driver Bundle" is `ACTIVE`. I also wonder if this is really valid to assume, why must the driver bundle be `ACTIVE` it should be enough for it to be `RESOLVED`?

**Comment by laeubi** [comment]
Still an issue.

**Comment by timothyjward** [comment]
This is tested already

* The tests check for the registration of the `DataSourceFactory` service. 
* Services can only be registered using a valid `BundleContext`. 
* A `BundleContext` is only valid for a starting/active/stopping bundle. 

Therefore it is necessary for the driver bundle to be started and no change is required in the tests.
