### ISSUE TITLE
Enable Github discussions?

### ISSUE THREAD

**Issue by laeubi** [osgi/osgi#535]
> GitHub Discussions is a collaborative communication forum for the community around an open source or internal project. Community members can ask and answer questions, share updates, have open-ended conversations, and follow along on decisions affecting the community's way of working.

https://docs.github.com/en/discussions

We use this in other Eclipse projects and it works quite well as a unified way to share ideas and ask questions that maybe later result in issues created or having an Q&A database.

I therefore like to suggest to enable this feature here.

**Comment by laeubi** [comment]
Examples:
- https://github.com/eclipse-tycho/tycho/discussions
- https://github.com/eclipse-m2e/m2e-core/discussions
- https://github.com/eclipse-equinox/equinox/discussions
- https://github.com/eclipse-platform/eclipse.platform/discussions
- ...

**Comment by bjhargrave** [comment]
As discussed at today's project call, I have turned on discussions. So we can now experiment with using them for a while.
