### ISSUE TITLE
[httpservice] upgrade to jakarta namespace

### ISSUE THREAD

**Issue by laeubi** [osgi/osgi#551]
[Pax web](https://github.com/ops4j/org.ops4j.pax.web) has a widely used [extension to Httpservice](https://github.com/ops4j/org.ops4j.pax.web/blob/main/pax-web-api/src/main/java/org/ops4j/pax/web/service/WebContainer.java) and even though `HttpService` is not considered "modern" anymore keeping it at the old `javax.*` namespace makes it effectivly unusable now that most containers move to the jakarat namespace.

I therefore like to propose to release one more version of the HttpService specification that simply moves `javax.*` --> `jakarta.*` namespace.

**Comment by grgrzybek** [comment]
Speaking from Pax Web perspective, I think it's good idea to keep `org.osgi.service.http` as kind of ancient legacy - just updated to `jakarta.servlet` packages with big, red not saying that Whiteboard approach is better now (even if the whiteboard extender pattern has some issues itself).

ops4j/org.ops4j.pax.web#1802 is work in progress, but the most important part of it is that `org.osgi.service.http.HttpService` interface is simply copied into Pax Web API bundle. Having it coming from the osgi CMPN API would make things simple.

There are at least two places where the ancient API is used:
* Jolokia: https://github.com/rhuss/jolokia/blob/v1.7.2/agent/osgi/src/main/java/org/jolokia/osgi/JolokiaActivator.java#L322-L325
* CXF: https://github.com/apache/cxf/blob/cxf-3.5.5/rt/transports/http/src/main/java/org/apache/cxf/transport/http/osgi/ServletExporter.java#L126

When working on ops4j/org.ops4j.pax.web#1802 (and ops4j/org.ops4j.pax.web#1803) I'll be adding feedback here.

**Comment by timothyjward** [comment]
in previous discussions we decided not to do this and to let the Http Service disappear. 

This update would be a huge amount of work as it would involve adding support (and tests) for all the features between the ancient Servlet version used by the Http Service and the latest version. Furthermore, the design of the Http Service follows an anti-pattern which we do not wish to promote. 

Anyone writing a new application should not use the Http Service, and anyone updating an existing application should move to the Servlet Whiteboard.

**Comment by grgrzybek** [comment]
If that's the final decision, I'd like to know if it's possible for Pax Web 10 (targetting `jakarta.servlet`) to use _old_ `org.osgi.service.http` package (and its `HttpService` and `HttpContext` interfaces) - I'd like to keep them as base interface of `org.ops4j.pax.web.service.WebContainer` extension interface (with 46 (!) additional methods for filters, listeners, jsps, session, cookies, SCIs, ...)?

**Comment by timothyjward** [comment]
It’s fine for people to implement and use the old interface, but it won’t be updated to use the new Jakarta API. In this case I would be adding the methods you want to the PAX interface and severing the link to the old specification. 

Note that all references and links to the Http Service have been removed from the Servlet whiteboard, including specified behaviour about service ids.

**Comment by laeubi** [comment]
> This update would be a huge amount of work as it would involve adding support (and tests) for all the features between the ancient Servlet version used by the Http Service and the latest version.

I must confess I'm not really understand this  part... what new features? the only change should be the HttpService interface accepting a `jakarta.Servlet` instead of `javax.Servlet` ...

**Comment by grgrzybek** [comment]
I'm stil preparing to run TCK tests on Pax Web related to "Web Applications Specification" (chapter 128) after migration to `jakarta.servlet`, so adding `HttpService` is not a big deal...

**Comment by bjhargrave** [comment]
If you need to support the HttpService with jakarta namespace, you will need a new package to hold this API. OSGi would not make an `org.osgi.service.http` version=2.0 package anyway. As you see in the RESTful services and servlet specs, we used a new package name. Since any users of a jarkarta-fied `HttpService` would need to use a new package name anyway, PAX can simply copy the `org.osgi.service.http` package contents into a PAX namespace package and modify the `javax` references to `jakarta`. Users can then migrate to the PAX namespace package for Jakarta use. (But PAX should not release packages in the osgi namespace.)

I don't support OSGi resurrecting HttpService and jakarta-fying it.

**Comment by laeubi** [comment]
> If you need to support the HttpService with jakarta namespace, you will need a new package to hold this API. OSGi would not make an org.osgi.service.http version=2.0 package anyway. 

Why not? Isn't that why packages are versioned? What is the purpose in always ever having only a v1.x version?

> I don't support OSGi resurrecting HttpService and jakarta-fying it.

I must confess I'm confused. When discussion about the removal of WAB it was argued that any removed spec can easily be "revived" if there is any interest, now this process is asked for it is rejected ...

**Comment by bjhargrave** [comment]
> Isn't that why packages are versioned? What is the purpose in always ever having only a v1.x version?

See https://github.com/osgi/bugzilla-archive/issues/2958 for some of the past discussion. But the OSGi experts some time ago reached general consensus that when a major version change happens that new package names should also be used. This allow those that are interested to import both old and new packages. This choice allows Felix Http to support both old Http Whiteboard and new Servlet whiteboard from a single implementation.

> When discussion about the removal of WAB it was argued that any removed spec can easily be "revived" if there is any interest, now this process is asked for it is rejected ...

You are not asking to revive it unchanged. You are asking for 2 things: revive it and then make a major change to it. I object to the latter and there is no point in reviving it unchanged.

**Comment by laeubi** [comment]
> See https://github.com/osgi/bugzilla-archive/issues/2958 and https://github.com/osgi/bugzilla-archive/issues/2949#issuecomment-622169502 for some of the past discussion. But the OSGi experts some time ago reached general consensus that when a major version change happens that new package names should also be used.

That seems really odd and actually resort to the "old" way of having version numbers in package names for evolution of an API, I must confess I always have though of actually making such practice unnecessary. There are many "major" breaking changes that might not affect the "whole universe" and inventing new package names seems not very helpful, strange enough the `javax`. > `jakarta` is exactly that kind of stuff that puts a lot of effort on libraries and I can't find many people that found this a great choice :-\

>  This choice allows Felix Http to support both old Http Whiteboard and new Servlet whiteboard from a single implementation.

Seems a very rare case where this is useful and seems to introduce a lot of maintenance efforts to support different (incompatible) versions in one release. But if it would be just a matter of rename the package I think that could be done here as well e.g. `org.osgi.service.http.jakarta` ...

> You are not asking to revive it unchanged. You are asking for 2 things: revive it and then make a major change to it. I object to the latter and there is no point in reviving it unchanged.

Isn't this effectively "once removed never revived" ...?

**Comment by grgrzybek** [comment]
> This choice allows Felix Http to support both old Http Whiteboard and new Servlet whiteboard from a single implementation.

That's true and convenient from the provider perspective. From the consumer perspective check this scenario - CXF 4 is based (as provider) on `jakarta.servlet` API and CXF 3 is for `javax.servlet`. It (CXF 4 doesn't support OSGi now, but may do it at some point in the future if there's a demand) uses `org.osgi.service.http.HttpService` to register a CXF servlet and now it'd need to pass an instance of `javax.servlet.Servlet` or `jakarta.servlet.Servlet`.

Adding to this another difference - like `orgi.osgi.service.http` in CXF 3 and e.g., `org.osgi.service.newhttp` in CXF 4 would be extra and unnecessary change.

So I agree with @laeubi here - `javax.servlet` to `jakarta.servlet` between version 4 and 5 is both major version and package name change, however it was only major version change with 2→3 and 3→4 case. So I'd treat `javax.servlet` → `jakarta.servlet` rather a (politically motivated) exception than a rule.

On the other hand:
> But the OSGi experts some time ago reached general consensus that when a major version change happens that new package names should also be used.

I can't argue with such decision even if it's quite weird...

**Comment by grgrzybek** [comment]
Back to the subject - whether to keep `HttpService` (in any package) or not.
I think chapter 102 (HttpService) is quite similar to chapter 128 (WebApplication) with one significant difference - it provides an API tied to `javax.servlet`.

If you want to keep chapter 128 (and I'm much much more certain that it's important), why not keep the HttpService? It *is* badly designed, it covers very little of the available _web elements_, it doesn't cover contexts at all (only `/`), but it's quite simple, straightforward and used in legacy code.

Also take this into account - OSGi CMPN 8.1, in the scope related to `javax` → `jakarta` migration **doesn't add any value** - it's just an effort forced by external, political decision which prevented to keep `javax` namespace.

Also mind that I'm maintaining Pax Web and only learning `bnd`, so I can try TCKs with Pax Web... I (and Pax Web) lags behind the TCKs, but it'll not remove HttpService support (as it's fundamentally built around them - even when implementing the Whiteboard spec).

**Comment by Natchaphonwongplianphan** [comment]
![Screenshot_20230110_075408](https://user-images.githubusercontent.com/69337668/211437706-c3ccf901-9683-438b-93a9-5d9afeaa88f5.jpg)
#นายณัชพล วงษ์เปลี่ยนผัน
 NATCHAPHON WONGPLIANPHAN#

**Comment by timothyjward** [comment]
> I must confess I'm not really understand this part... what new features? the only change should be the HttpService interface accepting a jakarta.Servlet instead of javax.Servlet ...

Given that the Http Service predates (and still does not support) Servlet Filters, there are quite a lot of new features that would need to be supported in a move to Jakarta.

**Comment by grgrzybek** [comment]
I'd like to suggest two paths:
# support chapter 102 (HttpService) with `jakarta.servlet` namespace, but only for current scope (registration of servlets and resources.
# get rid of chapter 102 entirely

Second option is obvious, but I see good reasons for option 1:
* if you want more (servlets, filters, listeners, prepprocessors, error pages), choose Whiteboard spec (chapter 140)
* if you want everything (the above + JSPs, SCIs, WebSockets, Welcome Files), choose Web Applications spec (chapter 128)
* if you want, well, only servlets, but you want to be on Jetty 10 / Tomcat 11 / Undertow 2.3 / Servlet API 5+, HttpService specification still plays its role. If CXF (4) considers bringing back OSGi support, it's easier to simply register one servlet than do it with Whiteboard. Of course it shouldn't be a problem for CXF to use Whiteboard, but imagine other projects/libraries - HttpService is quite straightforward.

**Comment by laeubi** [comment]
> Given that the Http Service predates (and still does not support) Servlet Filters, there are quite a lot of new features that would need to be supported in a move to Jakarta.

Why *must* they be supported? I really don't get this. as @grgrzybek  mentioned there are alternatives, for advanced use cases, but the bare minimum that is working for many use-cases is just a plain servlet and may libs offer such thing that can be integrated easily with `HttpService` ... with just a few lines of code I added JAX-RS support to my Application, and have in the past used this to integrate with Wicket, Vaadin, CXF ... so even though its not the most glorious service it serves its purpose.

**Comment by bjhargrave** [comment]
> Why _must_ they be supported?

The don't have to be, but you then have some explaining to do in the spec. The old spec supports Servlet 2.1 which does not have such things and so the old spec does not even have to mention them. All features of Servlet 2.1 are supported. But to update the spec to Servlet 5.0 (which is the first servlet spec based upon jakarta namespace), the updated spec will need to explain why many features in Servlet 5.0 are not supported. This is a bad look for a new specification.

**Comment by laeubi** [comment]
> I am unclear on how simply registering a servlet as a service (whiteboard) is not easier than using a service tracker to get the HttpService service and then call that service to register your servlet.

You don't need a service tracker, DS is perfectly suitable for this, also Blueprint, also CDI.... With whiteboard you simply has no control over *when* the servlet is registered, it might get register immediately, some time later, or probably never, so there are always different use-cases.

**Comment by bjhargrave** [comment]
> With whiteboard you simply has no control over _when_ the servlet is registered

Of course you have control. You can always decide when to register and unregister the servlet service.

**Comment by laeubi** [comment]
> > With whiteboard you simply has no control over _when_ the servlet is registered
> 
> Of course you have control. You can always decide when to register and unregister the servlet service.

Yes I can register it, but there is no guarantee it will actually be registered at the web-container (if ever), if there are many ones I can't easily decide to use one over the other ...

**Comment by laeubi** [comment]
> I don't understand this statement. 

What part exactly? The first part was because of @bjhargrave statement that one need to use servicetracker (what is just one way), the second was not specifically directed to Equinox or its implementation details.

In general Whiteboard is a great way to decouple things (especially listener), what is great for a listener (it is only used if there is a service collecting it and I don't need to know about it), is bad for other purpose, e.g. I **want** to publish my web-page (or give the user a log message: `WARNING no HttpService found, Website will NOT be available)`) or I want to choose to _which_ service of multiple available ones I want to register it (e.g. only to the one that serves the web console but not the the one that serves my web-frontend) .... this is nothing specific to `HttpService` but more generally if Whiteboard is the right approach for a service model or not.

**Comment by timothyjward** [comment]
> e.g. I want to publish my web-page (or give the user a log message: WARNING no HttpService found, Website will NOT be available))

If you need this knowledge couldn’t you track the runtime service for the whiteboard? Its presence tells you the whiteboard is up (same as http service). If you need more detail the runtime dtos exist.

**Comment by tjwatson** [comment]
> What part exactly?

All of it.

org.osgi.service.http.whiteboard.HttpWhiteboardConstants.HTTP_WHITEBOARD_TARGET can be used to target specific whiteboard implementations if there are multiple.

**Comment by timothyjward** [comment]
> > What part exactly?
> 
> All of it.
> 
> org.osgi.service.http.whiteboard.HttpWhiteboardConstants.HTTP_WHITEBOARD_TARGET can be used to target specific whiteboard implementations if there are multiple.

I use this feature a lot.

**Comment by laeubi** [comment]
As said, this was just a general statement that whiteboard is not good per-se (even though I often use that pattern) nor explicit usage of service, simple as that.

**Comment by grgrzybek** [comment]
I won't be defending HttpService. In practice there are no big differences between:
* Whiteboard: register a `javax|jakarta.servlet.Servlet` service and don't be sure when it'll be able to start responding to requests, and
* HttpService: register a tracker for `org.osgi.service.http.HttpService` and don't be sure when you'll be notified about it to be able to call `registerServlet()` with an instance

Speaking from CXF (if it wants to get back to OSGi) and Jolokia (https://github.com/rhuss/jolokia/pull/484#issuecomment-1375132916 - I'll be preparing PR for Jolokia soonish) I see two big benefits switching from HttpService to Whiteboard:
1. switch from dependency on osgi.cmpn (or org.osgi.service.http) to plain osgi.core (`BundleContext.registerService()`)
2. be able to configure target context (path) to register the servlet too. While Pax Web has lots of improvements related to cooperation of HttpService/Whiteboard/WAB web elements within single context (path), it's usually safer to have dedicated target (Jetty/Tomcat/Undertow specific) context for different applications. Remember - Pax Web doesn't use single "dispatcher servlet" but instead leverages actual Jetty/Tomcat/Undertow ServletContext implementations.

I won't be dying to spare HttpService specification ;)

**Comment by maho7791** [comment]
> As said, this was just a general statement that whiteboard is not good per-se (even though I often use that pattern) nor explicit usage of service, simple as that.

I don't agree with that. We permanently register/unregister Servlets as services programatically or via DS (e.g. Jersey, Vaadin, RAP, Jolokia, Swagger). The same applies for filters (Pac4J (OAuth), Logging Filter). It does not matter if the instances are DS components or just ordinary service registration with some service properties. I can introspect everything using the RuntimeService. 

What else do you need? I don't see a thing that is possible with HttpService and not possible with the Servlet Whiteboard. Vice verse it look different. 

I really understand that there are implementations, that still use the HttpService. As you argue, the user will lose trust in OSGi, when we deprecate specifications. The same applies to the fact, when we half-hearted provide a specifiaction, that is not compliant to the corresponding Servlet Specification. in addition to that the Servlet Whiteboard can be seen as successor of the HttpService. From this point of view I think HttpServie should be deprecated somewhen. That we've choosen this time based on the fact, that we have to switch to the jakarta namesspace somewhen.
