### ISSUE TITLE
org.osgi.service.event.annotations artifact?

### ISSUE THREAD

**Issue by laeubi** [osgi/osgi#567]
The scr annotations have an artifact at central:

https://mvnrepository.com/search?q=org.osgi.service.component.annotations

But I can't find one for `org.osgi.service.event.annotations` it seems part of:

https://mvnrepository.com/artifact/org.osgi/org.osgi.service.event/1.4.1

but a separate artifact would be more convenient.

The same applies to `org.osgi.service.event.propertytypes`

**Comment by stbischof** [comment]
Same for typed event admin which i recommend to use.

I never missed it. What so you think @timothyjward

**Comment by timothyjward** [comment]
With both the  event admin and type safe event APIs the relevant annotations (e.g. EventTopics) are designed to be applied to components providing services implementing one of the interfaces from the API. It therefore doesn’t make much sense to separate them into a different annotation jar as you would still need the API jar as well.

**Comment by laeubi** [comment]
My main interest is to use `@RequireEventAdmin` what *might* be used without using event admin in my bundle directly.

A similar case is `@RequireConfigurationAdmin` what can be useful if your component has require configuration policy, in that case the bundle never uses the config-admin directly, but still might want to require it (as without there can never be any configuration).

**Comment by timothyjward** [comment]
So I can see why `@RequireConfigurationAdmin` might be needed by a bundle which has no direct dependency on the API, but the same isn’t true of `@RequireEventAdmin`.

 If you need Event Admin you either need to use the Event Admin service to send events, or you need to use the EventHandler interface when registering a service. if you want to avoid these dependencies then you need to do a lot of reflection, at which point you’re well beyond the “helpful annotation” stage.

**Comment by laeubi** [comment]
Yes technically I agree, but from an organizational POV I think it would be good to have (source/class retained) annotations always in a separate module to be consistent across specifications.
That way it is also possible to explicitly *not* include them (e,g, when for whatever reason the annotations should not be used in a project).

For sure this is nothing one can't manage, but I found it quite convenient now the things are all separated.
