### ISSUE TITLE
[multi-release-bundle] provide a way to remove the Import-Package or Require-Capabilites header

### ISSUE THREAD

**Issue by laeubi** [osgi/osgi#573]
I have created a lightly advanced use-case of a MR-OSGi Bundle here:
- https://github.com/bndtools/bnd/pull/5581
 
and it has shown that there is one case not covered by the spec that us if the main manifest has a `Import-Package` or `Require-Capabilites` header, but the supplemental one should not.

This can happen if for example in the main part a library is used (--> package is imported) and later on java provides a build in (--> package import not required anymore).

My current idea would be to have a special syntax for example

`Import-Package: -`

in a supplemental manifest mean remove the header from the manifest.

**Comment by laeubi** [comment]
The example is here: https://github.com/bndtools/bnd/pull/5581/files I just noticed that BND generates no Imports for Java 9 only for Java 11 in the case I only use pure java API.

**Comment by timothyjward** [comment]
> I just noticed that BND generates no Imports for Java 9 

I believe this to be a bug in bnd's heuristics. Imports for `java.*` packages were added (in release 7 I think) to help support modular Java runtimes and not necessary in previous versions. Bnd uses the Java version as a proxy for framework version if no framework package is imported. Java 9 existed long enough ago that it *might* be used with an old framework, hence the heuristic to be "old".

In this case the heuristic is wrong as Multi-Release bundles were added in Core R7, which means that `java.*` packages *should* be imported by bundles using them.

**Comment by laeubi** [comment]
I created:
- https://github.com/bndtools/bnd/issues/5585

**Comment by pkriens** [comment]
bnd already [checks for the framework version it is importing](https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java#L330-L353) for this. However, the culprit seems to be that we check for Java 11 instead of Java 9. 

Since MRJ's are fully backward compatible, I think we should just keep the framework version check in there. Some stuff out there is surprisingly old and I do not see we gain anything. 

I am not sure I understand the EE check in bnd. Java  1.8 code can run on a >=9 EE with a >=7 Framework. The important part seems to be the Framework version since it can't properly handle Java imports.

**Comment by timothyjward** [comment]
> I am not sure I understand the EE check in bnd. Java 1.8 code can run on a >=9 EE with a >=7 Framework. The important part seems to be the Framework version since it can't properly handle Java imports.

The EE capability is provided by the framework, therefore your framework implementation must be new enough to understand what EE the version of Java that you’re using corresponds to. This couldn’t be done in advance as there was no way know what system packages to offer. 

If you are using Java 11 this limits you (in open source) to R7+ framework impls. Therefore a bundle requiring an EE of 11 or higher is overwhelmingly likely to imply a requirement for R7+. 

I only want to be certain that in the case where there is no framework api on the classpath at all we still get imports for `java.` packages by default.   Lid
