### ISSUE TITLE
[tck][webcontainer] ServletContextRegistrationTest#testMultiServletContextReg005 has wrong assumption on Bundle-SymbolicName

### ISSUE THREAD

**Issue by grgrzybek** [osgi/osgi#576]
When running `` with Pax Web 8 + Pax URL, I have this failure:
```
junit.framework.ComparisonFailure: expected:<tw1_0[ test ]war> but was:<tw1_0[_test_]war>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at junit.framework.TestCase.assertEquals(TestCase.java:260)
	at org.osgi.test.cases.webcontainer.util.validate.BundleManifestValidator.validateSymbolicName(BundleManifestValidator.java:120)
	at org.osgi.test.cases.webcontainer.util.validate.BundleManifestValidator.validate(BundleManifestValidator.java:89)
	at org.osgi.test.cases.webcontainer.junit.ServletContextRegistrationTest.registerWarBundleTest(ServletContextRegistrationTest.java:171)
	at org.osgi.test.cases.webcontainer.junit.ServletContextRegistrationTest.testMultiServletContextReg005(ServletContextRegistrationTest.java:136)
...
```

Pax URL is the component that changes the symbolic name using:
```java
localSymbolicName.replaceAll( "[^a-zA-Z_0-9.-]", "_" )
```

IMO there should be no space in `Bundle-SymbolicName` according to OSGi Core:
```
digit           ::= [0..9]
alpha           ::= [a..zA..Z]
alphanum        ::= alpha | digit
token           ::= ( alphanum | '_' | '-' )+
symbolic-name   ::= token ( '.' token )*
...
Bundle-SymbolicName ::= symbolic-name ( ';' parameter ) *
```

**Comment by grgrzybek** [comment]
Same for:
* `org.osgi.test.cases.webcontainer.junit.BundleSymbolicNameTest.testMultipleBundleSymbolicName001()` (here, `/` is treated as valid char in symbolic name)
* `org.osgi.test.cases.webcontainer.junit.BundleSymbolicNameTest.testBundleSymbolicName004()` 
* `org.osgi.test.cases.webcontainer.junit.BundleWebContextPathTest.testMultipleWebContextPath002()`
* `org.osgi.test.cases.webcontainer.junit.BundleWebContextPathTest.testMultipleWebContextPath003()`
* `org.osgi.test.cases.webcontainer.junit.BundleManifestHeadersTest.testMultipleManifestHeaders007()`
* `org.osgi.test.cases.webcontainer.junit.BundleManifestHeadersTest.testMultipleManifestHeaders005()`
* `org.osgi.test.cases.webcontainer.junit.BundleManifestHeadersTest.testManifestHeaders004()`

**Comment by stbischof** [comment]
@grgrzybek We are speaking about the spaces in this line?

https://github.com/osgi/osgi/blob/d38340f72c4770b601d6b7fe04dd60954c636735/org.osgi.test.cases.webcontainer/src/org/osgi/test/cases/webcontainer/junit/ServletContextRegistrationTest.java#L134

**Comment by grgrzybek** [comment]
@stbischof yes - Pax URL translates the provided symbolic name by replacing non-valid chars with `_`. OSGi Core mentions which chars are valid (see above for grammar excerpt), however I'm not sure what the Web Application spec says about rejecting/accepting/translating invalid `Bundle-SymbolicName`...

**Comment by stbischof** [comment]
@grgrzybek would be nice to recieve an PR on this. Switch from ` ` to `_`.

**Comment by grgrzybek** [comment]
#582 changes the symbolic names used by TCK tests for webcontainer specification to not contain spaces and `/` characters. The tests pass with existing Gemini/Virgo implementation as well as with Pax Web + Pax URL.
