### ISSUE TITLE
[tck][webcontainer] BundleWebContextPathTest#testWebContextPath010 uses unjustified assumption

### ISSUE THREAD

**Issue by grgrzybek** [osgi/osgi#577]
When running `org.osgi.test.cases.webcontainer.junit.BundleWebContextPathTest` with Pax Web 8 + Pax URL, I have this failure:
```
junit.framework.AssertionFailedError: Bundle-Classpath should be empty as it doesn't exist in the bundle before
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.TestCase.assertTrue(TestCase.java:192)
	at org.osgi.test.cases.webcontainer.junit.BundleWebContextPathTest.testWebContextPath010(BundleWebContextPathTest.java:173)
```

It's from a test with this comment:
```java
public void testWebContextPath010() throws Exception {
    // wmtw5.war is not a wab since it doesn't have Import-Package
    final Map<String, Object> options = createOptions(WEBCONTEXTPATH5);
...
```

Nothing in Chapter 128 of the specification says that if a WAB (a bundle with `Web-ContextPath`) doesn't have `Import-Package`, it's not valid...

> 128.3.1 WAB Definition 
>
> A WAB is differentiated from non Web Application bundles through the specification of the additional manifest header:
>
> ```Web-ContextPath ::= path```

> 128.4.4 WAB Modification
>
> The Web URL Handler can set or modify the Web-ContextPath of a WAB if the input source is already a bundle. It must be considered as a bundle when _**any**_ of the OSGi defined headers listed in [Table 128.3](https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.war.html#service.war-webbundle.url.parameters) is present in the bundle.

**Comment by maho7791** [comment]
I am not confident with the WAB specification. I just used the Jetty implementation for show case purposes.

The error  speaks about Bundle-Classpath directive and not Import-Package. 

We should discuss these issues at the next spec call. It might also be possible that the tests are not good enough.

@stbischof Would you like to move them to OSGi Test ;-)

**Comment by grgrzybek** [comment]
> @stbischof Would you like to move them to OSGi Test ;-)

I thought osgi/osgi-test is for the infra part of the tests, not for the tests themselves...

**Comment by maho7791** [comment]
OSGi-Test is JUnit5 Jupiter support for OSGi via extensions

**Comment by stbischof** [comment]
@grgrzybek improving the tests with spec-sections would helpful

**Comment by grgrzybek** [comment]
Virgo's `org.eclipse.gemini.web.internal.WebContainerUtils#isWebApplicationBundle()` is:
```java
public static boolean isWebApplicationBundle(BundleManifest manifest) {
    return specifiesBundleSymbolicName(manifest) || specifiesBundleVersion(manifest) || specifiesBundleManifestVersion(manifest)
        || specifiesImportPackage(manifest) || specifiesWebContextPath(manifest);
}
```

So:
1. `Bundle-SymbolicName` exists, or
2. `Bundle-Version` exists, or
3. `Bundle-ManifestVersion` exists, or
4. `Import-Package` exists and has at least one import, or
5. `Web-ContextPath` exists

the manifest from `wmtw5.war` passed is:
```
manifest = {org.eclipse.virgo.util.osgi.manifest.internal.StandardBundleManifest@4287} "Manifest-Version: 1.0\r\nBundle-Description: OSGi Web Container RFC 66 Compliance Test test war 5\r\n  with manifest somewhat pre-specified\r\nBundle-Vendor: Eclipse Foundation\r\nBundle-SymbolicName: org.osgi.test.cases.webcontainer.wmtw5\r\nBundle-Version: 1.0\r\nWeb-ContextPath: /wmtw5\r\nBundle-Name: org.osgi.test.cases.webcontainer.wmtw5\r\n\r\n"
 contents: org.eclipse.virgo.util.common.CaseInsensitiveMap  = {org.eclipse.virgo.util.common.CaseInsensitiveMap@4297}  size = 7
  {@4340} "Bundle-Description" -> {@4341} "OSGi Web Container RFC 66 Compliance Test test war 5 with manifest somewhat pre-specified"
  {@4342} "Bundle-Version" -> {@4343} "1.0"
  {@4344} "Web-ContextPath" -> {@4345} "/wmtw5"
  {@4346} "Bundle-Name" -> {@4347} "org.osgi.test.cases.webcontainer.wmtw5"
  {@4348} "Bundle-Vendor" -> {@4349} "Eclipse Foundation"
  {@4350} "Bundle-SymbolicName" -> {@4385} "org.osgi.test.cases.webcontainer.wmtw5"
  {@4352} "Manifest-Version" -> {@4353} "1.0"
```

So the first check gives WAB=true. There are three manifest transformers in Gemini/Virgo:
```
this.manifestTransformers = {org.eclipse.gemini.web.core.WebBundleManifestTransformer[3]@4396} 
 0 = {org.eclipse.gemini.web.internal.url.SpecificationWebBundleManifestTransformer@4402} 
 1 = {org.eclipse.gemini.web.internal.url.DefaultsWebBundleManifestTransformer@4403} 
 2 = {org.eclipse.gemini.web.internal.url.SystemBundleExportsImportingWebBundleManifestTransformer@4404}
```

`org.eclipse.gemini.web.internal.url.SpecificationWebBundleManifestTransformer`:
* throws IllegalArgumentException if WAB and options specify `Bundle-SymbolicName`
* throws IllegalArgumentException if WAB and options specify `Bundle-Version`
* throws IllegalArgumentException if WAB and options specify `Bundle-ManifestVersion`
* throws IllegalArgumentException if WAB and options specify `Bundle-ClassPath` - doesn't modify/generate `Bundle-ClassPath` if not WAB
* throws IllegalArgumentException if WAB and options specify `Import-Package`
* throws IllegalArgumentException if WAB and options specify `Export-Package`
* sets `Web-ContextPath` is among the options

`org.eclipse.gemini.web.internal.url.DefaultsWebBundleManifestTransformer`:
* only if non-WAB or proprietary `org-eclipse-gemini-web-DefaultWABHeaders` option is set (defaults to `false`) generate default symbolic name, `Bundle-ManifestVersion`, `Bundle-ClassPath` and `Import-Package`

`org.eclipse.gemini.web.internal.url.SystemBundleExportsImportingWebBundleManifestTransformer`:
* only if non-WAB or proprietary `org-eclipse-gemini-web-DefaultWABHeaders` option is set (defaults to `false`) call `SystemBundleExportsImportingWebBundleManifestTransformer#addImportsForSystemBundleExports()

**Comment by grgrzybek** [comment]
This:
```java
/*
 * verify valid deployOptions overwrite original manifest Web-ContextPath
 */
```

comment is copied all over `org.osgi.test.cases.webcontainer.junit.BundleWebContextPathTest`...

**Comment by grgrzybek** [comment]
`BundleWebContextPathTest#testWebContextPath010` is correct, but the comments were a bit confusing. ops4j/org.ops4j.pax.url#418 fixes the test on Pax URL side.
