### ISSUE TITLE
HttpWhiteboard and Servlet 4.0

### ISSUE THREAD

**Issue by juergen-albert** [osgi/osgi#59]
The Servlet 4.0 Spec is out for a while now and I stumbled over a couple libraries already, that build upon it. I've no real idea what the changes are at the moment, that warranted a major version change, but the whiteboard becomes incompatible with newer Servlets.

Thus I think we need to have a closer look at it. Has anybody already worked with the new Spec?

Maybe we can come up with a fancy idea, how to maintain backward compatibility.

**Comment by bjhargrave** [comment]
Project call: Add contract for JavaServlet 2.1, and use in org.osgi.service.http companion jar.

Updated Java contracts to cover Jakarta EE 8  (this includes Servlet 4.0).

**Comment by bjhargrave** [comment]
I think the answer here is to go straight to the version of Servlet in Jakarta EE 9 as part of the namespace change. See #54.

**Comment by bjhargrave** [comment]
#381 supersedes this.
