### ISSUE TITLE
Hash pin actions on github workflows

### ISSUE THREAD

**Issue by joycebrum** [osgi/osgi#592]
Hi I'm Joyce from Google and I'm working on helping many open source projects on improving their supply chain security posture.

## Description

I would like to suggest a security practice recommended by the [OpenSSF Scorecard][scorecard-repo] which is to hash pin CI dependencies to prevent from tag renaming attacks. This means hash pinning GitHub Workflow actions.

Although the actions that need to be hash pinned on osgi are Github Owned Actions, it is still recommended to hash pin them since they are open sourced and are exposed to the same threat vectors any open source project is. Besides, this is currently the only way of using github actions as immutable releases.

Also it might be important to notice that the dependabot, that is already enabled, is able to update both the hash and the comment version related to it.

Let me know if you are open to evaluate those changes and I'll submit the PR ASAP. 

Any questions or concerns just let me know.
Thanks!

## Additional Context

A tag renaming attack is a type of attack whereby an attacker:
- Hijack an action.
- Upload a malicious version.
- Replace existing tags with malicious versions.

See [Why you should pin actions by commit hash](https://blog.rafaelgss.dev/why-you-should-pin-actions-by-commit-hash) for a better understanding of a tag renaming attack.

[scorecard-repo]: https://github.com/ossf/scorecard

**Comment by stbischof** [comment]
Hi,

i see the value of this. 

https://github.com/osgi/osgi/blob/a9dcd22545576260f3571c1db996a5b8d6548e55/.github/workflows/bnd-test.yml#LL56
https://github.com/osgi/osgi/blob/a9dcd22545576260f3571c1db996a5b8d6548e55/.github/workflows/bnd-test.yml#LL58
https://github.com/osgi/osgi/blob/a9dcd22545576260f3571c1db996a5b8d6548e55/.github/workflows/bnd-test.yml#LL64

@timothyjward  any other opinions on this that replacing this with hashes (dependabot also supports hash updates )
