### ISSUE TITLE
Gecko JakartaRS Implementation contribution

### ISSUE THREAD

**Issue by maho7791** [osgi/osgi#593]
For the contribution of the JakartaRS Whiteboard implementation to the OSGi Technology project  we will need.
It is based upon Jersey and the current default implementation for the TCK.

* Git repository name
* Package naming

I suggest *jakartars-osgi* as repository name (jersey-osgi is misleading)
For the package naming I suggest *org.eclipse.ot.rest*.

If there are any other ideas, please comment this issue

**Comment by timothyjward** [comment]
> I suggest jakartars-osgi as repository name (jersey-osgi is misleading)

**Comment by maho7791** [comment]
The Eclipse issues is:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3297

**Comment by maho7791** [comment]
Committed initial contribution:

https://github.com/osgi/jakartarest-osgi

**Comment by maho7791** [comment]
Re-Opened to discuss BJ's comment:

https://github.com/osgi/jakartarest-osgi/issues/1

**Comment by timothyjward** [comment]
I believe that this can now be closed? @maho7791 @stbischof
