### ISSUE TITLE
GroupId registration for org.eclipse.technology.osgi 

### ISSUE THREAD

**Issue by stbischof** [osgi/osgi#612]
Corresponding to the discussion on https://github.com/osgi/osgi/discussions/599

@maho7791 will care about the registration of groupid for `org.eclipse.technology.osgi`.

**Comment by maho7791** [comment]
The vote is closed in https://github.com/osgi/osgi/discussions/599

**Comment by maho7791** [comment]
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3522

**Comment by maho7791** [comment]
The groupId *org.eclipse.osgi-technology* was proposed from the releng team. So we took it.
The JIPP instance is already configured.
Here is a configuration help:
https://wiki.eclipse.org/Jenkins#How_can_artifacts_be_deployed_to_OSSRH_.2F_Maven_Central.3F
https://maven.apache.org/plugins/maven-gpg-plugin/usage.html#Configure_passphrase_in_settings.xml
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3522

This issue can be closed, from my side
