### ISSUE TITLE
[technology] repo for implementation on jakarta.xml.ws-osgi

### ISSUE THREAD

**Issue by stbischof** [osgi/osgi#614]
In parallel to the design for  jakarta.xml.ws spec (see PR https://github.com/osgi/osgi/pull/588 ) we would start to work on an implementation. This could challenge the spec the spec.

For this we would need a repo: `jakarta.xml.ws-osgi`  

this is same as for jaxrs:  https://github.com/osgi/jakartarest-osgi

@timothyjward do you think is may be useful to also create an other one for the web-socket implementation?

**Comment by maho7791** [comment]
I would take the chance to shortly hear opinions to:

https://github.com/osgi/jakartarest-osgi/issues/1

Personally I have no strong opinion regarding *-osgi*. Even if the organisation is already osgi, the *-osgi* in the repo name avoids misunderstandings. On the other hand it is also a duplicate.

In any case we should take care about a consistent naming for new projects.

**Comment by stbischof** [comment]
No need for -osgi on my site

**Comment by stbischof** [comment]
so name should be: `org.eclipse.technology.osgi.jakarta.xml.ws`?

**Comment by timothyjward** [comment]
Is this still relevant? Can it be closed?
