### ISSUE TITLE
Enable OpenSSF Scorecard Action

### ISSUE THREAD

**Issue by joycebrum** [osgi/osgi#626]
Hi again, I'd like to suggest the adoption of the [OpenSSF Scorecard Action](https://github.com/ossf/scorecard-action)

It verifies periodically whether the project is following some security practices (such as having a Security Policy or not using any vulnerable dependency). This action brings the following benefits:

- provide feedback on how to improve the security practice on the [Security Dashboard](https://github.com/ossf/scorecard-action#code-scanning-alerts)
- the badge on the readme provides transparency to users over the project security practice (the current score is really great, being the in the top 0.1% greatest scores between more than 10k projects and the top 2.9% among only the critical ones (criticality_score > 0.5).
    - [How badges helps you put your security score front and center](https://securityscorecard.com/blog/how-badges-helps-you-put-your-security-score-front-and-center/)  

Let me know if the implementation is welcome and I can submit a PR.

Thanks.

**Comment by stbischof** [comment]
Hi,

that sounds interesting. A PR would be nice. We have to look if and what Token are Required and how the Eclipse foundation handles this.
