### ISSUE TITLE
Clarify inheritance semantics of annotations ProviderType and ConsumerType

### ISSUE THREAD

**Issue by kwin** [osgi/osgi#643]
Currently it is not clear from the javadoc of either [ProviderType](https://docs.osgi.org/javadoc/osgi.annotation/8.0.0/org/osgi/annotation/versioning/ProviderType.html) or [ConsumerType](https://docs.osgi.org/javadoc/osgi.annotation/8.0.0/org/osgi/annotation/versioning/ConsumerType.html) which role annotation wins in case multiple ones apply (from the same package).

According to Bnd it is nearest wins, so in case you have class `A` extending `B`. And `B` extending `C`, the role of `B` overwrites the role of `C` (i.e. if `C` is marked as ProviderType but `B` is not having any role annotation at all it is assumed to be the default (i.e. ConsumerType) and `A` has a broad import-package version range).

Also if you have `A` both extending `B` as well as implementing `Z` and `Z` is a ProviderType, the ProviderType role wins (only relevant if `Z` and `B` are located in the same package).

**Comment by kwin** [comment]
Also with regards to conflicting types in package and class it is not clear how it should behave. 
In case the package is marked as `@ProviderType` and the class within is marked as `@ConsumerType` what is the role?

**Comment by juergen-albert** [comment]
@kwin We discussed the whole thing for half an hour and have some ideas. Just to help us along a bit: Can you provide a small dummy class example to make this easier to grasp?

**Comment by juergen-albert** [comment]
> According to Bnd it is nearest wins, so in case you have class A extending B. And B extending C, the role of B overwrites the role of C (i.e. if C is marked as ProviderType but B is not having any role annotation at all it is assumed to be the default (i.e. ConsumerType) and A has a broad import-package version range).

The Annotations are not marked with `@Inherited` and thus the extending classes/interfaces don't know about the original annotation. By the default they thus become ContsumerType if not marked otherwise. 

It would make sense to mention this in the javadoc.

**Comment by kwin** [comment]
I added an example with README in https://github.com/kwin/providerconsumerexample which outlines the inconsistencies here.

**Comment by bjhargrave** [comment]
There is no inheritance for these annotations.
