### ISSUE TITLE
Jersey3.x resource not resolving in OSGi (old compendium version 5.0.0)  - getting http 404

### ISSUE THREAD

**Issue by AmolFasate** [osgi/osgi#653]
We are migrating our jetty, jersey, Apache cxf library to latest version for our OSGi project and for all the rest API/resource we are getting 404

Here is the current OSGi and jar version
1. org.osgi.core old version 6.0.0
1. org.apache.felix.http.jetty old version 4.2.12
2. glassfish-jersey old version 2.13

Migrated jar version
1.org.apache.felix.http.jetty new version 5.1.6
2. glassfish-jersey new version 3.1.1

After migration we were able to compile and deploy the code into Apache Felix 
- For compilation we are registering servlets by wrapping(Apache Felix HTTP wrappers) them into javax attached the snapshot for reference.
- We obseved that resources are being registered but REST endpoints are not accessible. 
- Looks like Unable to register jakarta servlet instance with OSGI HTTP service. 

We are trying to understand the root cause, and looks like Jersey3.x using Jakarta and we have to follow the Whiteboard Specification for Jakarta mentioned in the
OSGi reference link https://docs.osgi.org/specification/osgi.cmpn/8.1.0/service.jakartars.html
For that we need to migrate OSGi compendium version to R8.1 (Minimum)

Will R9 compendium support this feature? if yes, when we can expect R9 release and also it would be helpful if someone suggest alternative way.

![image](https://github.com/osgi/osgi/assets/144648534/043ef4e6-48a1-48c0-be99-fb099f5e9d35)

**Comment by stbischof** [comment]
Hi @AmolFasate,

i am not sure that I understand you issue.

Whens is about working with Rest/Servlets there are 2 recommended ways.
- Registering REST Resources on JaxRsWhiteboard: [SPEC](https://docs.osgi.org/specification/osgi.cmpn/8.1.0/service.jakartars.html) [impl](https://github.com/osgi/jakartarest-osgi)
- Registering Servlets on HttpServletWhiteboard: [SPEC](https://docs.osgi.org/specification/osgi.cmpn/8.1.0/service.servlet.html) [impl](https://github.com/apache/felix-dev/tree/master/http)

I would not register the Servlet on the HttpService nowadays.

I am not sure about witch `features` you want to have supportes in R9.

**Comment by AmolFasate** [comment]
we are using compendium(v5.0.0) to register javax.servlet.Servlet objects with the Http Service by using the

HttpService interface (Chapter 102) reference link https://docs.osgi.org/download/r5/osgi.cmpn-5.0.0.pdf
 
Below is the HttpService interface code for compendium(v5.0.0) 
 
![image](https://github.com/osgi/osgi/assets/144648534/17ee0353-6e09-455b-86e2-e6e4a894d34b)
 
But after migration Jersey3.x which internally use Jakarta and we have to follow the Whiteboard Specification for Jakarta mentioned in the 

OSGi reference link https://docs.osgi.org/specification/osgi.cmpn/8.1.0/service.jakartars.html, 

so we are replacing JavaEE references with JakartaEE and to register my servlets with the Servlet Whiteboard implementation by registering them as Whiteboard services. 
It means Servlet implementations are registered in the Service Registry under the jakarta.servlet.Servlet interface.

Till Compendium 8 we are registering HttpService interface(chapter 102) 
example: httpService.registerServlet(String,javax.servlet.Servlet,Dictionary,HttpContext).

In Compendium R8.1 there are Resource Service Properties used by Jakarta RESTful Web Services resources registered as Whiteboard services.
example: osgi.jakartars.resource.JakartarsResource

@Component(service = MyResource.class, scope = ServiceScope.PROTOTYPE)
@JakartarsResource     
public class MyResource {
  
    @Path(“foo”)
    @GET
    public Promise<String> getFoo() {
        Promise<String> p = doLongRunningTaskAsynchronously();
        return p;
    }
}
    
 
For that we need to migrate OSGi compendium version to R8.1 (Minimum), 

Will R9 compendium support same above mentioned feature? if yes, when we can expect R9 release and also for R8.1 when will this be released to maven central.

**Comment by maho7791** [comment]
Hi,OSGi Compendium is just a collection of specifications. The working group releases just the API. For compendium 8.1 this happened last year.Chapter 151 Version 2 describes the Jakarta based whiteboard for Rest services. 140 describes the Jakarta based Servlet whiteboard with version 2.0.for both you'll need an implementation. Glassfush Jersey 3 ist just the implementation for the Java Rest specification. To use it in OSGi manner, you need an additional whiteboard implementation.The one I linked in the last post, is such an implementation that is based on Jersey 3. Just for clarification this has no relation to the Http Service from chapter 102. This specification is deprecated and will not move to jakarta. A follow up specification, look into Servlet whiteboard in chapter 140, that is jakarta compliant with Apache Felix Jetty 5, I think.Regards,Mark Hoffmann M.A. Dipl.-Betriebswirt (FH) CEO/CTO Phone:   +49 3641 384 910 0 Mobile:  +49 175 701 2201 E-Mail: ***@***.*** Web: www.datainmotion.de Data In Motion Consulting GmbH Kahlaische Strasse 4 07745 Jena Germany Geschäftsführer/CEO Mark Hoffmann Jürgen Albert Jena HRB 513025 Steuernummer 162/107/05779 USt-Id DE310002614
-------- Ursprüngliche Nachricht --------Von: AmolFasate ***@***.***> Datum: 21.12.23  11:48  (GMT+01:00) An: osgi/osgi ***@***.***> Cc: Subscribed ***@***.***> Betreff: Re: [osgi/osgi] Jersey3.x resource not resolving in OSGi (old compendium version 5.0.0)  - getting http 404 (Issue #653) 
we are using compendium(v5.0.0) to register javax.servlet.Servlet objects with the Http Service by using the
HttpService interface (Chapter 102) reference link https://docs.osgi.org/download/r5/osgi.cmpn-5.0.0.pdf
Below is the HttpService interface code for compendium(v5.0.0)
image.png (view on web)
But after migration Jersey3.x which internally use Jakarta and we have to follow the Whiteboard Specification for Jakarta mentioned in the
OSGi reference link https://docs.osgi.org/specification/osgi.cmpn/8.1.0/service.jakartars.html,
so we are replacing JavaEE references with JakartaEE and to register my servlets with the Servlet Whiteboard implementation by registering them as Whiteboard services.
It means Servlet implementations are registered in the Service Registry under the jakarta.servlet.Servlet interface.
Till Compendium 8 we are registering HttpService interface(chapter 102)
example: httpService.registerServlet(String,javax.servlet.Servlet,Dictionary,HttpContext).
In Compendium R8.1 there are Resource Service Properties used by Jakarta RESTful Web Services resources registered as Whiteboard services.
example: osgi.jakartars.resource.JakartarsResource
@component(service = MyResource.class, scope = ServiceScope.PROTOTYPE)
@JakartarsResource
public class MyResource {
@Path(“foo”)
@GET
public Promise<String> getFoo() {
    Promise<String> p = doLongRunningTaskAsynchronously();
    return p;
}

}
For that we need to migrate OSGi compendium version to R8.1 (Minimum),
Will R9 compendium support same above mentioned feature? if yes, when we can expect R9 release and also for R8.1 when will this be released to maven central.

**Comment by stbischof** [comment]
I agree with Mark.

Just one correction. HttpService is not deprecated. Its just not recommend to use it anymore to Register Servlet. This could be  done with the Whiteboard Patter  that servlet and jaxrs Whiteboards use.

No need to use jersey and the osgi jaxrs spec  for just register a Whiteboard.
See my example above for manually registering a Servlet on bundlecontext.

**Comment by AmolFasate** [comment]
Thanks Mark, Stefan for reply/clarification.
Need to discuss with team on this will get back, 
Can you please also let me know when R8.1/R9 release will this be released to maven central.

**Comment by stbischof** [comment]
''''
 <dependency>
				<groupId>org.osgi</groupId>
				<artifactId>org.osgi.service.jakartars</artifactId>
				<version>2.0.0</version>
			 </dependency>

'''

**Comment by AmolFasate** [comment]
I am not seeing R8.1 release for compendium in maven central attached screen shot below,

![image](https://github.com/osgi/osgi/assets/144648534/0d5306b2-7bb6-4c3b-a274-d9ff22cf29c7)


Please let me know if repository got changed?

**Comment by maho7791** [comment]
Hi, as mentioned before, compendium consist of several specifications. So there is no single compendium jar. In former times this existed, but not anymore.Instead the API's of the specifications are released, like before. It is cleaner to specify the dependencies you really need, even at build time.RegardsMark Hoffmann M.A. Dipl.-Betriebswirt (FH) CEO/CTO Phone:   +49 3641 384 910 0 Mobile:  +49 175 701 2201 E-Mail: ***@***.*** Web: www.datainmotion.de Data In Motion Consulting GmbH Kahlaische Strasse 4 07745 Jena Germany Geschäftsführer/CEO Mark Hoffmann Jürgen Albert Jena HRB 513025 Steuernummer 162/107/05779 USt-Id DE310002614
-------- Ursprüngliche Nachricht --------Von: AmolFasate ***@***.***> Datum: 22.12.23  06:44  (GMT+01:00) An: osgi/osgi ***@***.***> Cc: Mark Hoffmann ***@***.***>, Comment ***@***.***> Betreff: Re: [osgi/osgi] Jersey3.x resource not resolving in OSGi (old compendium version 5.0.0)  - getting http 404 (Issue #653) 
I am not seeing R8.1 release for compendium in maven central attached screen shot below,
image.png (view on web)
Please let me know if repository got changed?

**Comment by stbischof** [comment]
The cmpm release is a release of a selection of apis as  "book".


The big benefit of not using a cmpm jar as api is ,that you do Not have to update all code and libs and dependencies if you just need a newer Version of one osgi chapter.

**Comment by timothyjward** [comment]
Just as an update - there was a new release of the Jakarta REST whiteboard implementation from https://github.com/osgi/jakartarest-osgi a few days ago. This is already [in Maven Central ](https://mvnrepository.com/artifact/org.eclipse.osgi-technology.rest). You will want the implementation and an "adapter" to add it to whatever web container you want to use. For example the Servlet Whiteboard adapter will deploy on top of an OSGi Servlet Whiteboard implementation, or the Jetty adapter will launch a Jetty instance.
