### ISSUE TITLE
Make osgi.annotation bundle a JPMS module to simplify making OSGi-friendly libraries

### ISSUE THREAD

**Issue by pdolezal** [osgi/osgi#663]
I suggest to add `module-info.java` to [`osgi.annotation`](https://central.sonatype.com/artifact/org.osgi/osgi.annotation), so that it is an actual JPMS module.

This would help making OSGi-friendly libraries easier. Currently, a library can be built as a JPMS module and have an OSGi manifest entries, but those entries must be supplied externally (e.g., via the configuration of Maven Bundle Plugin). It is not possible to use the annotations to specify package versions and type roles, because the compiler requires the dependency to be a module (as it checks the module metadata consistency). Maybe there is a dirty trick, but I haven't found it, and even if a workaround exists, I suppose it is better to support a really natural way.

With this change, it would be possible to have `osgi.annotation` as a regular dependency, even for JPMS. The library's `module-info.java` would be just extended like this to please the compiler:

```
module com.example.library {
    requires static osgi.annotation; // static makes it compile-time only, not necessary for run time
    // More entries follow
}
```

The change on the `osgi.annotation` side would be probably something like adding `module-info.java` with the following content:
```
module osgi.annotation {
    exports org.osgi.annotation.versioning;
    exports org.osgi.annotation.bundle;
}
```

**Comment by tjwatson** [comment]
> I never would like to see osgi.annotation in my runtime.

The Java compiler is requiring the module-info, not the runtime.  I don't see the addition of a module-info to be related to if the module will be used at runtime or not.  As stated the user would have:

```java
requires static osgi.annotation; // static makes it compile-time only, not necessary for run time
```

Making the presence of the `osgi.annotation` module not a requirement at runtime. I see no reason to not include the module-info for the annotation bundle.

**Comment by pdolezal** [comment]
@tjwatson replied correctly. Here is a small reproducer to demonstrate the issue:  [com.example.api.zip](https://github.com/osgi/osgi/files/14015372/com.example.api.zip)

If you delete the `module-info.java`, the project can be compiled and produces a regular bundle. But with the `module-info.java` present, the compiler complains that the annotations are not visible and refuses to proceed.

If `osgi.annotation` were also a regular JPMS module, a `requires` clause could be added and refer to the module (as a `static` dependency) and the compiler would be happy. Turning the artifact into a JPMS module could be done by adding `module-info.java`, or adding the `Automatic-Module-Name` manifest header. The latter approach is already used by `org.osgi.framework` artifact (I suppose it was forced by the desire to find the `FrameworkFactory` interface via `ServiceLoader` in a (JPMS) modular application), but it has the disadvantage that module name depends on the artifact file name, which makes it fragile. With the `module-info.java` any valid module name can be specified, e.g., `org.osgi.annotation`, which might be a better module name.

Anyway, I see no problem with turning the annotations in a JPMS module, no matter which way is preferred. It would definitely remove an obstacle for producing libraries that could be used directly as OSGi bundles or JPMS modules.

**Comment by timothyjward** [comment]
This seems like a good idea - I assume that it should be applied to other annotation jars published by the OSGi build as well?

**Comment by stbischof** [comment]
One way could be to use the atomic bundles.

Could you please try to use these:
- org.osgi.annotation.bundle
 -org.osgi.annotation.versioning
 
 
 ```
 <dependency>
    <groupId>org.osgi</groupId>
    <artifactId>org.osgi.annotation.bundle</artifactId>
    <version>2.0.0</version>
    <scope>provided</scope>
</dependency>
```

@tjwatson can give more information

**Comment by tjwatson** [comment]
Discussed at the specification call today.  It was pointed out that the `osgi.annotation` JAR is not a proper bundle.  This evident by the fact that it has `osgi.unresolvable` requirement making it unresolvable.  We do not plan to add proper JPMS module info to such "uber" style bundles named osgi.* such as `osgi.cmpn`, `osgi.core` and `osgi.annotation`.  Instead you should be using one of the "proper" OSGi bundles which do have the `Automatic-Module-Name` header already.

For `osgi.annotation` that would be `org.osgi.annotation.bundle` and/or `org.osgi.annotation.versioning` which already have the `Automatic-Module-Name` header.

At some point we may add `module-info.class` to all of our "proper" OSGi bundles, but that will be only to the ones where we already have the `Automatic-Module-Name` header.

**Comment by pdolezal** [comment]
@tjwatson Alright, thanks for the resolution 👍 It would be great if official OSGi resources mentioned or recommended practices how to make dual JPMS/OSGi modules. I guess that other developers might struggle with that or remain ignorant, which in turn hurts OSGi technology.
