### ISSUE TITLE
Redundant code in converter implementation.

### ISSUE THREAD

**Issue by folarte** [osgi/osgi#673]
While investigating a previous report I noticed lines 466-489 of method 	
`private <T> T convertToDTO(Class< ? > sourceCls, Class< ? > targetAsCls, InternalConverter converter)` 
in class `org.osgi.util.converter.ConvertingImpl`
have what seems like a leftover from some refactoring:
```
				Field f = null;
				try {
					f = targetAsCls.getField(fieldName);
				} catch (NoSuchFieldException e) {
					// There is no field with this name
					if (keysIgnoreCase) {
						// If enabled, try again but now ignore case
						for (Field fs : targetAsCls.getFields()) {
							if (fs.getName().equalsIgnoreCase(fieldName)) {
								f = fs;
								break;
							}
						}

						if (f == null) {
							for (Field fs : targetAsCls.getFields()) {
								if (fs.getName().equalsIgnoreCase(fieldName)) {
									f = fs;
									break;
								}
							}
						}
					}
				}
```
In `if(keysIgnoreCase)` the second loop inside the `if(f==null)` seems to be identical. Given f is initialized to null before the try, it should be null in the catch, had it been altered in the first loop it must be not-null ( as its value, fs,  is dereferenced before ). If it has not been altered, it is null, and the second identical loop should not alter it either.

This seems like a conversion from null-testing to exceptions was interrumpted part way and someone forgot to erase the second if.

**Comment by stbischof** [comment]
can you do a PR to fix this?

**Comment by folarte** [comment]
Sorry for the delay. Totally lost in github. I have managed to find the PR, looked at the commit and submitted an approval to it. I do not know if this is OK. I also do not know if I should close this.
