### ISSUE TITLE
[DS] ComponentPropertyTypes should support Optional

### ISSUE THREAD

**Issue by mikerumpf** [osgi/osgi#743]
I am not sure if this feature request is somehow related to https://github.com/osgi/osgi/issues/584 but It would be nice if you could use Optionals in ComponentPropertyTypes:

`@ComponentPropertyType
 public @interface Config {

  Optional<String> name();
}`

So if the property is not set you would get Optional.empty().

**Comment by stbischof** [comment]
You may ask OpenJDK to tech this to the compiler.
```
Invalid type Optional for the annotation attribute CronExpression.optVal; only primitive type, String, Class, annotation, enumeration are permitted or 1-dimensional arrays thereof
```

Your @Config annotation wouldn't be able to work.

**Comment by mikerumpf** [comment]
Thanks for the info. I should have known myself...

**Comment by stbischof** [comment]
What was your goal?

If its about configadmin and metatype,You may use Interfaces Generate the metatype info using the -felixextension in bnd and Convert the config map into Interface using the configutator

**Comment by mikerumpf** [comment]
yeah, it was about reading out the actual configuration in the activate method of the component. Would have been nice to specify a value as optional. What do you mean by the converter?

**Comment by stbischof** [comment]
org.osgi.util.converter
https://docs.osgi.org/specification/osgi.cmpn/7.0.0/util.converter.html

Take a Map from you activate method and converter.convert(map).to(InterfaceWithOptional.class)

**Comment by laeubi** [comment]
one can specify a default value:


```
@ComponentPropertyType
public @interface Config {

       String name() default "";
}
```

that is not particular "nice" but often suitable

**Comment by mikerumpf** [comment]
Yes, that's the way we use stuff like that. Introducing extra-interfaces for use with the Converter-API feels a little too boilerplate IMHO. Also, you would lose the default statement.

**Comment by mikerumpf** [comment]
But thanks for the info/help.

**Comment by stbischof** [comment]
if your company really needs an interceptor/plugin mechanism for
- activate/deactivate for Components
- bind/update/unbind for References

You may talk with @juergen-albert or @maho7791 . I header them talking about that.

This would be out of the current spec, but depending on how much work/money you would put in, there may be ways to specify this.

Your are also welcome to the spec calls.

https://calendar.google.com/calendar/u/0/embed?src=c_fh3lhb5p0l29f6phu2ndifh4a4@group.calendar.google.com&ctz=America/New_York
