### ISSUE TITLE
[DS] Provide a way to manually mark a component as failed in order to enable retries

### ISSUE THREAD

**Issue by kwin** [osgi/osgi#778]
Currently the only way to indicate a failed DS component initialization is by throwing an exception in its activate() method/constructor (compare with #776). 

However long running initializations are supposed to happen asynchronously (compare with https://stackoverflow.com/a/57250631). 

How is it possible to manually put the component back to the registered state (in case of some potentially recoverable exception)? Just waiting indefinitely is not an option and I need an easy way to retry if the asynchronous initialization failed for whatever reason.

I want to put back my delayed component into the `Registered` state (https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.component.html#service.component-delayed.component) or my immediate component back into the `Unsatisfied` state (https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.component.html#d0e39569)

However the `ComponentContext` only has `enableComponent(...)` and `disableComponent(...)` which is never reset by the framework automatically. I need some API to put the component back to the previous state such that is is
a) started when a service it is implementing is request again (delayed component)
b) started when the configuration is changed (immediate component)

**Comment by laeubi** [comment]
In such a case you should make your component not implementing any service, then you can (after the async init) register the component and/or retry the init after a while.

**Comment by laeubi** [comment]
But these are competing things, I think in general that would require more a change in the DS spec to mark a component as "asynchronous" what on the other hand is incompatible with the service lookup.

So you have actually the following choices:

1. Block the activation for a while then you can see the activation errors in the DTO
2. Decouple the "async part" and register a service async, that is actually how it should work
3. Do init in the background (e.g. with a `CompletableFuture`) and join it at the time where a call into your service is made, in that case you will get the error at the caller site.

**Comment by laeubi** [comment]
> However the `ComponentContext` only has `enableComponent(...)` and `disableComponent(...)` which is never reset by the framework automatically. I need some API to put the component back to the previous state such that is is

From the `ComponentContext` you can fetch the `ComponentInstance` and then call `dispose` what should work as you like, your **component instance (!)** gets disposed and on the next change it should be recreated.

**Comment by tjwatson** [comment]
There is also `org.osgi.service.component.runtime.ServiceComponentRuntime.disableComponent(ComponentDescriptionDTO)` and `org.osgi.service.component.runtime.ServiceComponentRuntime.enableComponent(ComponentDescriptionDTO)` that should force the component back to the resolved state.
